In [1]:
sentence_list = ["I am Ashish", "I am Monika"]

In [2]:
lower_sentence_list = [x.lower() for x in sentence_list]

In [3]:
print(lower_sentence_list)

['i am ashish', 'i am monika']

In [4]:
import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/ashishgour/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [5]:
english_stopwords = stopwords.words("english")
print(english_stopwords)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [6]:
my_sentence = "I am a about to go above again on the table and we are of the table now"

In [7]:
fresh_sentence = ' '.join([word for word in my_sentence.split() if word not in english_stopwords])
print(fresh_sentence)

I go table table

In [8]:
import re

In [9]:
my_string = r"I am on the table now"
print(re.sub("on", "above", my_string))

I am above the table now

In [10]:
pattern = r"^I"
print(re.search(pattern, my_string))

<re.Match object; span=(0, 1), match='I'>

In [11]:
list_1 = ["name", "age", "address"]
list_2 = [word for word in list_1 if word != "age"]
list_2

['name', 'address']

In [12]:
list_3 = [3,4,5,6]
list_4 = [num * 2 for num in list_3 if num % 2 == 0]
list_4

[8, 12]

In [13]:
import re
list_5 = ["I am ashish", "you are not ashish", "He is mukesh", "I am not ashish but suresh"]
list_6 = [re.sub(r"ashish", "suresh", word) for word in list_5 if re.search(r"^I.*h$", word) ]
list_6

['I am suresh', 'I am not suresh but suresh']

In [14]:
import re
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
nltk.download('punkt')
nltk.download('punkt_tab') 
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/ashishgour/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/ashishgour/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/ashishgour/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [15]:
data = pd.read_csv("tripadvisor_hotel_reviews.csv")
data.head()

                                              Review  Rating
0  nice hotel expensive parking got good deal sta...       4
1  ok nothing special charge diamond member hilto...       2
2  nice rooms not 4* experience hotel monaco seat...       3
3  unique, great stay, wonderful time hotel monac...       5
4  great stay great stay, went seahawk game aweso...       5

In [16]:
data["reviews_lowercase"] = data["Review"].str.lower()
data.head()

,Review,Rating,reviews_lowercase
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso..."

In [17]:
english_stopwords.remove("not")

In [18]:

def remove_stopword(text):
    return ' '.join([word for word in text.split() if word not in english_stopwords])

data["reviews_no_stopwords"] = data["reviews_lowercase"].apply(remove_stopword)

In [19]:
data.head()

,Review,Rating,reviews_lowercase,reviews_no_stopwords
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4* experience hotel monaco seat...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso..."

In [20]:
def remove_punc_star(text):
    text = re.sub(r"\*", "star", text)
    return re.sub(r"[^\w\s]","", text)
data["reviews_nostopwords_no_punc"] = data["reviews_no_stopwords"].apply(remove_punc_star)

In [21]:
data.head()

,Review,Rating,reviews_lowercase,reviews_no_stopwords,reviews_nostopwords_no_punc
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4star experience hotel monaco s...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...",unique great stay wonderful time hotel monaco ...
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...",great stay great stay went seahawk game awesom...

In [22]:
data["reviews_tokenized"] = data["reviews_nostopwords_no_punc"].apply(word_tokenize)

In [23]:
data.head()

,Review,Rating,reviews_lowercase,reviews_no_stopwords,reviews_nostopwords_no_punc,reviews_tokenized
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,"[nice, hotel, expensive, parking, got, good, d..."
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,"[ok, nothing, special, charge, diamond, member..."
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4star experience hotel monaco s...,"[nice, rooms, not, 4star, experience, hotel, m..."
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...",unique great stay wonderful time hotel monaco ...,"[unique, great, stay, wonderful, time, hotel, ..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...",great stay great stay went seahawk game awesom...,"[great, stay, great, stay, went, seahawk, game..."

In [24]:
data["reviews_tokenized"][0]

['nice',
 'hotel',
 'expensive',
 'parking',
 'got',
 'good',
 'deal',
 'stay',
 'hotel',
 'anniversary',
 'arrived',
 'late',
 'evening',
 'took',
 'advice',
 'previous',
 'reviews',
 'valet',
 'parking',
 'check',
 'quick',
 'easy',
 'little',
 'disappointed',
 'nonexistent',
 'view',
 'room',
 'room',
 'clean',
 'nice',
 'size',
 'bed',
 'comfortable',
 'woke',
 'stiff',
 'neck',
 'high',
 'pillows',
 'not',
 'soundproof',
 'like',
 'heard',
 'music',
 'room',
 'night',
 'morning',
 'loud',
 'bangs',
 'doors',
 'opening',
 'closing',
 'hear',
 'people',
 'talking',
 'hallway',
 'maybe',
 'noisy',
 'neighbors',
 'aveda',
 'bath',
 'products',
 'nice',
 'not',
 'goldfish',
 'stay',
 'nice',
 'touch',
 'taken',
 'advantage',
 'staying',
 'longer',
 'location',
 'great',
 'walking',
 'distance',
 'shopping',
 'overall',
 'nice',
 'experience',
 'pay',
 '40',
 'parking',
 'night']

In [25]:
ps = PorterStemmer()
def stem(words):
    return [ps.stem(word) for word in words]
data["reviews_stammed"] = data["reviews_tokenized"].apply(stem)

In [26]:
data.head()

,Review,Rating,reviews_lowercase,reviews_no_stopwords,reviews_nostopwords_no_punc,reviews_tokenized,reviews_stammed
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,"[nice, hotel, expensive, parking, got, good, d...","[nice, hotel, expens, park, got, good, deal, s..."
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,"[ok, nothing, special, charge, diamond, member...","[ok, noth, special, charg, diamond, member, hi..."
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4star experience hotel monaco s...,"[nice, rooms, not, 4star, experience, hotel, m...","[nice, room, not, 4star, experi, hotel, monaco..."
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...",unique great stay wonderful time hotel monaco ...,"[unique, great, stay, wonderful, time, hotel, ...","[uniqu, great, stay, wonder, time, hotel, mona..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...",great stay great stay went seahawk game awesom...,"[great, stay, great, stay, went, seahawk, game...","[great, stay, great, stay, went, seahawk, game..."

In [27]:
lem = WordNetLemmatizer()
def lem_words(words):
    return [lem.lemmatize(word) for word in words]
data["reviews_lem"] = data["reviews_tokenized"].apply(lem_words)

In [28]:
data.head()

,Review,Rating,reviews_lowercase,reviews_no_stopwords,reviews_nostopwords_no_punc,reviews_tokenized,reviews_stammed,reviews_lem
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,"[nice, hotel, expensive, parking, got, good, d...","[nice, hotel, expens, park, got, good, deal, s...","[nice, hotel, expensive, parking, got, good, d..."
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,"[ok, nothing, special, charge, diamond, member...","[ok, noth, special, charg, diamond, member, hi...","[ok, nothing, special, charge, diamond, member..."
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4star experience hotel monaco s...,"[nice, rooms, not, 4star, experience, hotel, m...","[nice, room, not, 4star, experi, hotel, monaco...","[nice, room, not, 4star, experience, hotel, mo..."
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...",unique great stay wonderful time hotel monaco ...,"[unique, great, stay, wonderful, time, hotel, ...","[uniqu, great, stay, wonder, time, hotel, mona...","[unique, great, stay, wonderful, time, hotel, ..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...",great stay great stay went seahawk game awesom...,"[great, stay, great, stay, went, seahawk, game...","[great, stay, great, stay, went, seahawk, game...","[great, stay, great, stay, went, seahawk, game..."

In [29]:
tokens_clean = sum(data["reviews_lem"], [])
tokens_clean

['nice',
 'hotel',
 'expensive',
 'parking',
 'got',
 'good',
 'deal',
 'stay',
 'hotel',
 'anniversary',
 'arrived',
 'late',
 'evening',
 'took',
 'advice',
 'previous',
 'review',
 'valet',
 'parking',
 'check',
 'quick',
 'easy',
 'little',
 'disappointed',
 'nonexistent',
 'view',
 'room',
 'room',
 'clean',
 'nice',
 'size',
 'bed',
 'comfortable',
 'woke',
 'stiff',
 'neck',
 'high',
 'pillow',
 'not',
 'soundproof',
 'like',
 'heard',
 'music',
 'room',
 'night',
 'morning',
 'loud',
 'bang',
 'door',
 'opening',
 'closing',
 'hear',
 'people',
 'talking',
 'hallway',
 'maybe',
 'noisy',
 'neighbor',
 'aveda',
 'bath',
 'product',
 'nice',
 'not',
 'goldfish',
 'stay',
 'nice',
 'touch',
 'taken',
 'advantage',
 'staying',
 'longer',
 'location',
 'great',
 'walking',
 'distance',
 'shopping',
 'overall',
 'nice',
 'experience',
 'pay',
 '40',
 'parking',
 'night',
 'ok',
 'nothing',
 'special',
 'charge',
 'diamond',
 'member',
 'hilton',
 'decided',
 'chain',
 'shot',
 '20th',
 'anniversary',
 'seattle',
 'start',
 'booked',
 'suite',
 'paid',
 'extra',
 'website',
 'description',
 'not',
 'suite',
 'bedroom',
 'bathroom',
 'standard',
 'hotel',
 'room',
 'took',
 'printed',
 'reservation',
 'desk',
 'showed',
 'said',
 'thing',
 'like',
 'tv',
 'couch',
 'ect',
 'desk',
 'clerk',
 'told',
 'oh',
 'mixed',
 'suite',
 'description',
 'kimpton',
 'website',
 'sorry',
 'free',
 'breakfast',
 'got',
 'kidding',
 'embassy',
 'suit',
 'sitting',
 'room',
 'bathroom',
 'bedroom',
 'unlike',
 'kimpton',
 'call',
 'suite',
 '5',
 'day',
 'stay',
 'offer',
 'correct',
 'false',
 'advertising',
 'send',
 'kimpton',
 'preferred',
 'guest',
 'website',
 'email',
 'asking',
 'failure',
 'provide',
 'suite',
 'advertised',
 'website',
 'reservation',
 'description',
 'furnished',
 'hard',
 'copy',
 'reservation',
 'printout',
 'website',
 'desk',
 'manager',
 'duty',
 'not',
 'reply',
 'solution',
 'send',
 'email',
 'trip',
 'guest',
 'survey',
 'not',
 'follow',
 'email',
 'mail',
 'guess',
 'tell',
 'concerned',
 'guestthe',
 'staff',
 'ranged',
 'indifferent',
 'not',
 'helpful',
 'asked',
 'desk',
 'good',
 'breakfast',
 'spot',
 'neighborhood',
 'hood',
 'told',
 'hotel',
 'gee',
 'best',
 'breakfast',
 'spot',
 'seattle',
 '12',
 'block',
 'away',
 'convenient',
 'hotel',
 'not',
 'know',
 'exist',
 'arrived',
 'late',
 'night',
 '11',
 'pm',
 'inside',
 'run',
 'bellman',
 'busy',
 'chating',
 'cell',
 'phone',
 'help',
 'bagsprior',
 'arrival',
 'emailed',
 'hotel',
 'inform',
 '20th',
 'anniversary',
 'half',
 'really',
 'picky',
 'wanted',
 'make',
 'sure',
 'good',
 'got',
 'nice',
 'email',
 'saying',
 'like',
 'deliver',
 'bottle',
 'champagne',
 'chocolate',
 'covered',
 'strawberry',
 'room',
 'arrival',
 'celebrate',
 'told',
 'needed',
 'foam',
 'pillow',
 'arrival',
 'champagne',
 'strawberry',
 'foam',
 'pillow',
 'great',
 'room',
 'view',
 'alley',
 'high',
 'rise',
 'building',
 'good',
 'not',
 'better',
 'housekeeping',
 'staff',
 'cleaner',
 'room',
 'property',
 'impressed',
 'left',
 'morning',
 'shopping',
 'room',
 'got',
 'short',
 'trip',
 '2',
 'hour',
 'bed',
 'comfortablenot',
 'good',
 'acheat',
 'control',
 '4',
 'x',
 '4',
 'inch',
 'screen',
 'bring',
 'green',
 'shine',
 'directly',
 'eye',
 'night',
 'light',
 'sensitive',
 'tape',
 'controlsthis',
 'not',
 '4',
 'start',
 'hotel',
 'clean',
 'business',
 'hotel',
 'super',
 'high',
 'rate',
 'better',
 'chain',
 'hotel',
 'seattle',
 'nice',
 'room',
 'not',
 '4star',
 'experience',
 'hotel',
 'monaco',
 'seattle',
 'good',
 'hotel',
 'nt',
 '4star',
 'levelpositives',
 'large',
 'bathroom',
 'mediterranean',
 'suite',
 'comfortable',
 'bed',
 'pillowsattentive',
 'housekeeping',
 'staffnegatives',
 'ac',
 'unit',
 'malfunctioned',
 'stay',
 'desk',
 'disorganized',
 'missed',
 '3',
 'separate',
 'wakeup',
 'call',
 'concierge',
 'busy',
 'hard',
 'touch',
 'nt',
 'provide',
 'guidance',
 'special',
 'requeststv',
 'hard',
 'use',
 'ipod',
 'sound',
 'dock',
 'suite',
 'non',
 'functioning',
 'decided',
 'book',
 'mediterranean',
 'suite',
 '3',
 'night',
 'weekend',
 'stay',
 '1st',
 'choice',
 'rest',
 'party',
 'filled',
 'comparison',
 'w',
 'spent',
 '45',
 'night',
 'larger',
 'square',
 'footage',
 'room',
 'great',
 'soaking',
 'tub',
 'whirlpool',
 'jet',
 'nice',
 'showerbefore',
 'stay',
 'hotel',
 'arrange',
 'car',
 'service',
 'price',
 '53',
 'tip',
 'reasonable',
 'driver',
 'waiting',
 'arrivalcheckin',
 'easy',
 'downside',
 'room',
 'picked',
 '2',
 'person',
 'jacuzi',
 'tub',
 'bath',
 'accessory',
 'salt',
 'bubble',
 'bath',
 'nt',
 'stay',
 'night',
 'got',
 '121a',
 'checked',
 'voucher',
 'bottle',
 'champagne',
 'nice',
 'gesture',
 'fish',
 'waiting',
 'room',
 'impression',
 'room',
 'huge',
 'open',
 'space',
 'felt',
 'room',
 'big',
 'tv',
 'far',
 'away',
 'bed',
 'chore',
 'change',
 'channel',
 'ipod',
 'dock',
 'broken',
 'disappointingin',
 'morning',
 'way',
 'asked',
 'desk',
 'check',
 'thermostat',
 'said',
 '65f',
 '74',
 '2',
 'degree',
 'warm',
 'try',
 'cover',
 'face',
 'night',
 'bright',
 'blue',
 'light',
 'kept',
 'got',
 'room',
 'night',
 'no',
 '1st',
 'drop',
 'desk',
 'called',
 'maintainence',
 'came',
 'look',
 'thermostat',
 'told',
 'play',
 'setting',
 'happy',
 'digital',
 'box',
 'wo',
 'nt',
 'work',
 'asked',
 'wakeup',
 '10am',
 'morning',
 'nt',
 'happen',
 'called',
 'later',
 '6pm',
 'nap',
 'wakeup',
 'forgot',
 '10am',
 'wakeup',
 'morning',
 'yep',
 'forgottenthe',
 'bathroom',
 'facility',
 'great',
 'room',
 'surprised',
 'room',
 'sold',
 'whirlpool',
 'bath',
 'tub',
 'nt',
 'bath',
 'amenity',
 'great',
 'relax',
 'water',
 'jet',
 'going',
 'unique',
 'great',
 'stay',
 'wonderful',
 'time',
 'hotel',
 'monaco',
 'location',
 'excellent',
 'short',
 'stroll',
 'main',
 'downtown',
 'shopping',
 'area',
 'pet',
 'friendly',
 'room',
 'showed',
 'sign',
 'animal',
 'hair',
 'smell',
 'monaco',
 'suite',
 'sleeping',
 'area',
 'big',
 'striped',
 'curtain',
 'pulled',
 'closed',
 'nice',
 'touch',
 'felt',
 'cosy',
 'goldfish',
 'named',
 'brandi',
 'enjoyed',
 'nt',
 'partake',
 'free',
 'wine',
 'coffeetea',
 'service',
 'lobby',
 'thought',
 'great',
 'feature',
 'great',
 'staff',
 'friendly',
 'free',
 'wireless',
 'internet',
 'hotel',
 'worked',
 'suite',
 '2',
 'laptop',
 'decor',
 'lovely',
 'eclectic',
 'mix',
 'patten',
 'color',
 'palatte',
 'animal',
 'print',
 'bathrobe',
 'feel',
 'like',
 'rock',
 'star',
 'nice',
 'nt',
 'look',
 'like',
 'sterile',
 'chain',
 'hotel',
 'hotel',
 'personality',
 'excellent',
 'stay',
 'great',
 'stay',
 'great',
 'stay',
 'went',
 'seahawk',
 'game',
 'awesome',
 'downfall',
 'view',
 'building',
 'nt',
 'complain',
 'room',
 'huge',
 'staff',
 'helpful',
 'booked',
 'hotel',
 'website',
 'seahawk',
 'package',
 'charge',
 'parking',
 'got',
 'voucher',
 'taxi',
 'problem',
 'taxi',
 'driver',
 'nt',
 'want',
 'accept',
 'voucher',
 'barely',
 'spoke',
 'english',
 'funny',
 'thing',
 'speak',
 'arabic',
 'called',
 'started',
 'making',
 'comment',
 'girlfriend',
 'cell',
 'phone',
 'buddy',
 'took',
 'second',
 'realize',
 'said',
 'fact',
 'speak',
 'language',
 'face',
 'priceless',
 'as',
 'told',
 'said',
 'large',
 'city',
 'told',
 'head',
 'doorman',
 'issue',
 'called',
 'cab',
 'company',
 'promply',
 'answer',
 'nt',
 'apologized',
 'offered',
 'pay',
 'taxi',
 'buck',
 '2',
 'mile',
 'stadium',
 'game',
 'plan',
 'taxi',
 'return',
 'going',
 'humpin',
 'great',
 'walk',
 'nt',
 'mind',
 'right',
 'christmas',
 'wonderful',
 'light',
 'homeless',
 'stowed',
 'away',
 'building',
 'entrance',
 'leave',
 'police',
 'presence',
 'not',
 'greatest',
 'area',
 'stadium',
 'activity',
 '7',
 'block',
 'pike',
 'street',
 'waterfront',
 'great',
 'coffee',
 'shop',
 'way',
 'hotel',
 'mantained',
 'foyer',
 'awesome',
 'wine',
 'tasting',
 'available',
 'evening',
 'best',
 'dog',
 'taking',
 'st',
 'bernard',
 'time',
 'family',
 'safe',
 'hotel',
 'located',
 'service',
 'desk',
 'room',
 'bathroom',
 'huge',
 'jetted',
 'tub',
 'huge',
 'funny',
 'house',
 'keeping',
 'walked',
 'girlfriend',
 'getting',
 'dressed',
 'nt',
 'hear',
 'knock',
 'turn',
 'service',
 'screamed',
 'girlfriend',
 'scream',
 'hit',
 'floor',
 'laughing',
 'started',
 'talking',
 'spanish',
 'worked',
 'place',
 'recommend',
 'price',
 'check',
 'online',
 'deal',
 'good',
 'not',
 'better',
 'besite',
 'contains',
 'deal',
 'voucher',
 'travel',
 'website',
 'nt',
 'tell',
 'love',
 'monaco',
 'staff',
 'husband',
 'stayed',
 'hotel',
 'crazy',
 'weekend',
 'attending',
 'memorial',
 'service',
 'best',
 'friend',
 'husband',
 'celebrating',
 '12th',
 'wedding',
 'anniversary',
 'talk',
 'mixed',
 'emotion',
 'booked',
 'suite',
 'hotel',
 'monte',
 'carlos',
 'loaned',
 'beautiful',
 'fantanned',
 'goldfish',
 'named',
 'joliet',
 'weekend',
 'visited',
 'dog',
 'worked',
 'desk',
 'human',
 'companion',
 'room',
 'decorated',
 'nicely',
 'couch',
 'used',
 'pillow',
 'loccitane',
 'bath',
 'amenity',
 'welcome',
 'sight',
 'room',
 'quiet',
 'peaceful',
 'wireless',
 'internet',
 'access',
 'wonderful',
 'server',
 'went',
 'morning',
 'leaving',
 'problem',
 'printing',
 'boarding',
 'pass',
 'afternoon',
 'reception',
 'serf',
 'oenophilesatisfying',
 'wine',
 'australia',
 'scrumptious',
 'cooky',
 'restaurant',
 'closed',
 'renovation',
 'stay',
 'finally',
 'ate',
 'food',
 'good',
 'drink',
 'better',
 'word',
 'caution',
 'restaurant',
 'larger',
 'person',
 'not',
 'sit',
 'booth',
 'wo',
 'nt',
 'fit',
 '56',
 '125',
 'lb',
 'husband',
 '59',
 '175',
 'table',
 'smackagainst',
 'stomach',
 'couple',
 'inch',
 'space',
 'mighty',
 'uncomfortable',
 'patron',
 'larger',
 'pregnant',
 'bad',
 'design',
 'opinion',
 'place',
 'decorated',
 'funky',
 'welcoming',
 'way',
 'metal',
 'wood',
 'handblown',
 'glass',
 'light',
 'fixture',
 'expect',
 'seattle',
 'capital',
 'glass',
 'art',
 'industry',
 'definitely',
 'stay',
 'reason',
 'cozy',
 'stay',
 'rainy',
 'city',
 'husband',
 'spent',
 '7',
 'night',
 'monaco',
 'early',
 'january',
 '2008',
 'business',
 'trip',
 'chance',
 'come',
 'ridewe',
 'booked',
 'monte',
 'carlo',
 'suite',
 'proved',
 'comfortable',
 'longish',
 'stay',
 'room',
 '905',
 'located',
 'street',
 'building',
 'street',
 'noise',
 'not',
 'problem',
 'view',
 'interesting',
 'room',
 'building',
 'look',
 'dank',
 'alley',
 'midsection',
 'large',
 'office',
 'building',
 'suite',
 'comfortable',
 'plenty',
 'room',
 'spread',
 'bathroom',
 'attractive',
 'squeaky',
 'clean',
 'small',
 'comparison',
 'generous',
 'proportion',
 ...]

In [30]:
unigrams = (pd.Series(nltk.ngrams(tokens_clean, 1)).value_counts())
print(unigrams)

(hotel,)           292
(room,)            275
(great,)           126
(not,)             122
(stay,)             95
                  ...
(175,)               1
(smackagainst,)      1
(2x,)                1
(80,)                1
(connected,)         1
Name: count, Length: 2589, dtype: int64

In [31]:
import spacy

/opt/anaconda3/envs/nlp_env/lib/python3.12/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(

In [32]:
string = "Hello, My name is ashish. I am a software engineer"

In [33]:
nlp = spacy.load("en_core_web_sm")

In [34]:
doc = nlp(string)
doc

Hello, My name is ashish. I am a software engineer

In [35]:
data = [{"token": token.text, "pos": token.pos_} for token in doc]
data

[{'token': 'Hello', 'pos': 'INTJ'},
 {'token': ',', 'pos': 'PUNCT'},
 {'token': 'My', 'pos': 'PRON'},
 {'token': 'name', 'pos': 'NOUN'},
 {'token': 'is', 'pos': 'AUX'},
 {'token': 'ashish', 'pos': 'ADJ'},
 {'token': '.', 'pos': 'PUNCT'},
 {'token': 'I', 'pos': 'PRON'},
 {'token': 'am', 'pos': 'AUX'},
 {'token': 'a', 'pos': 'DET'},
 {'token': 'software', 'pos': 'NOUN'},
 {'token': 'engineer', 'pos': 'NOUN'}]

In [36]:
df = pd.DataFrame(data)
df

       token    pos
0      Hello   INTJ
1          ,  PUNCT
2         My   PRON
3       name   NOUN
4         is    AUX
5     ashish    ADJ
6          .  PUNCT
7          I   PRON
8         am    AUX
9          a    DET
10  software   NOUN
11  engineer   NOUN

In [37]:
df["pos"].value_counts()

pos
NOUN     3
PUNCT    2
PRON     2
AUX      2
INTJ     1
ADJ      1
DET      1
Name: count, dtype: int64

In [38]:
df["token"].value_counts()

token
Hello       1
,           1
My          1
name        1
is          1
ashish      1
.           1
I           1
am          1
a           1
software    1
engineer    1
Name: count, dtype: int64

In [39]:
df[df["pos"] == "NOUN"]

       token   pos
3       name  NOUN
10  software  NOUN
11  engineer  NOUN

In [40]:
df[df["pos"].isin(["NOUN", "AUX"])]

       token   pos
3       name  NOUN
4         is   AUX
8         am   AUX
10  software  NOUN
11  engineer  NOUN

In [41]:
df.groupby("pos")["token"].count()

pos
ADJ      1
AUX      2
DET      1
INTJ     1
NOUN     3
PRON     2
PUNCT    2
Name: token, dtype: int64

In [42]:
df.groupby("token")["pos"].count()

token
,           1
.           1
Hello       1
I           1
My          1
a           1
am          1
ashish      1
engineer    1
is          1
name        1
software    1
Name: pos, dtype: int64

In [43]:
df.groupby("pos")

In [44]:
df.sort_values(by="token", ascending=True)

       token    pos
1          ,  PUNCT
6          .  PUNCT
0      Hello   INTJ
7          I   PRON
2         My   PRON
9          a    DET
8         am    AUX
5     ashish    ADJ
11  engineer   NOUN
4         is    AUX
3       name   NOUN
10  software   NOUN

In [45]:
google_text = "Google was founded on September 4, 1998, by computer scientists Larry Page and Sergey Brin while they were PhD students at Stanford University in California. Together they own about 14% of its publicly listed shares and control 56% of its stockholder voting power through super-voting stock. The company went public via an initial public offering (IPO) in 2004. In 2015, Google was reorganized as a wholly owned subsidiary of Alphabet Inc. Google is Alphabet's largest subsidiary and is a holding company for Alphabet's internet properties and interests. Sundar Pichai was appointed CEO of Google on October 24, 2015, replacing Larry Page, who became the CEO of Alphabet. On December 3, 2019, Pichai also became the CEO of Alphabet."

In [46]:
ner_doc = nlp(google_text)

In [47]:
print(ner_doc.ents)

(Google, September 4, 1998, Larry Page, Sergey Brin, PhD, Stanford University, California, about 14%, 56%, IPO, 2004, 2015, Google, Alphabet Inc., Alphabet, Alphabet, Sundar Pichai, Google, October 24, 2015, Larry Page, Alphabet, December 3, 2019, Pichai, Alphabet)

In [48]:
for word in ner_doc.ents:
    print(word.text, word.label_)

Google ORG
September 4, 1998 DATE
Larry Page PERSON
Sergey Brin PERSON
PhD WORK_OF_ART
Stanford University ORG
California GPE
about 14% PERCENT
56% PERCENT
IPO ORG
2004 DATE
2015 DATE
Google ORG
Alphabet Inc. ORG
Alphabet ORG
Alphabet ORG
Sundar Pichai PERSON
Google ORG
October 24, 2015 DATE
Larry Page PERSON
Alphabet GPE
December 3, 2019 DATE
Pichai PERSON
Alphabet GPE

In [49]:
data_ner = [(word.text, word.label_) for word in ner_doc.ents]

In [50]:
df_ner = pd.DataFrame(data_ner, columns=["entity", "label"])

In [51]:
df_ner.head(10)

                entity        label
0               Google          ORG
1    September 4, 1998         DATE
2           Larry Page       PERSON
3          Sergey Brin       PERSON
4                  PhD  WORK_OF_ART
5  Stanford University          ORG
6           California          GPE
7            about 14%      PERCENT
8                  56%      PERCENT
9                  IPO          ORG

In [52]:
len(df)

12

In [53]:
print(google_text)

Google was founded on September 4, 1998, by computer scientists Larry Page and Sergey Brin while they were PhD students at Stanford University in California. Together they own about 14% of its publicly listed shares and control 56% of its stockholder voting power through super-voting stock. The company went public via an initial public offering (IPO) in 2004. In 2015, Google was reorganized as a wholly owned subsidiary of Alphabet Inc. Google is Alphabet's largest subsidiary and is a holding company for Alphabet's internet properties and interests. Sundar Pichai was appointed CEO of Google on October 24, 2015, replacing Larry Page, who became the CEO of Alphabet. On December 3, 2019, Pichai also became the CEO of Alphabet.

In [54]:
print(doc)

Hello, My name is ashish. I am a software engineer

In [55]:
print(doc)

Hello, My name is ashish. I am a software engineer

In [56]:
for token in doc:
   print(token.text, token.dep_, token.head.text)

Hello intj is
, punct is
My poss name
name nsubj is
is ROOT is
ashish acomp is
. punct is
I nsubj am
am ROOT am
a det engineer
software compound engineer
engineer attr am

In [57]:
from textblob import TextBlob

In [58]:
sent1 = "This is too good & bad"

In [59]:
blob = TextBlob(sent1)
blob.sentiment

Sentiment(polarity=5.551115123125783e-17, subjectivity=0.6333333333333333)

In [60]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

In [61]:
texts = ["I love this", "I hate this"]
labels = [1, 0]
vectors = TfidfVectorizer()

In [62]:
X = vectors.fit_transform(texts)

In [63]:
model = LogisticRegression()

In [64]:
model.fit(X, labels)

LogisticRegression()

In [65]:
print(X)

  (0, 1)	0.8148024746671689
  (0, 2)	0.5797386715376657
  (1, 2)	0.5797386715376657
  (1, 0)	0.8148024746671689

In [66]:
new_Input = ["I love this product", "I dont like this very much", "Its good but could be better"]

In [67]:
X_new = vectors.transform(new_Input)

In [68]:
model.predict(X_new)

array([1, 0, 0])

In [69]:
print("Train shape:", X.shape)
print("New shape:", X_new.shape)

Train shape: (2, 3)
New shape: (3, 3)

In [70]:
from sklearn.feature_extraction.text import CountVectorizer

In [71]:
bow_vector = CountVectorizer()

In [72]:
docs = [
    "cricket bat ball match",
    "football goal player match",
    "python code algorithm data",
    "cricket code data match"
]

In [73]:
bow_maxtrix = bow_vector.fit_transform(docs)

In [74]:
print(bow_maxtrix)

  (0, 4)	1
  (0, 2)	1
  (0, 1)	1
  (0, 8)	1
  (1, 8)	1
  (1, 6)	1
  (1, 7)	1
  (1, 9)	1
  (2, 10)	1
  (2, 3)	1
  (2, 0)	1
  (2, 5)	1
  (3, 4)	1
  (3, 8)	1
  (3, 3)	1
  (3, 5)	1

In [75]:
bow_vector.get_feature_names_out()

array(['algorithm', 'ball', 'bat', 'code', 'cricket', 'data', 'football',
       'goal', 'match', 'player', 'python'], dtype=object)

In [76]:
bow_maxtrix.toarray()

array([[0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
       [1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0]])

In [77]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [78]:
tf_vector = TfidfVectorizer()

In [79]:
tf_matrix = tf_vector.fit_transform(docs)

In [80]:
tf_matrix.toarray()

array([[0.        , 0.57457953, 0.57457953, 0.        , 0.4530051 ,
        0.        , 0.        , 0.        , 0.36674667, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.5417361 , 0.5417361 , 0.34578314, 0.5417361 ,
        0.        ],
       [0.55528266, 0.        , 0.        , 0.43779123, 0.        ,
        0.43779123, 0.        , 0.        , 0.        , 0.        ,
        0.55528266],
       [0.        , 0.        , 0.        , 0.52303503, 0.52303503,
        0.52303503, 0.        , 0.        , 0.42344193, 0.        ,
        0.        ]])

In [81]:
tf_vector.get_feature_names_out()

array(['algorithm', 'ball', 'bat', 'code', 'cricket', 'data', 'football',
       'goal', 'match', 'player', 'python'], dtype=object)

In [82]:
fake_news_df = pd.read_csv("fake_news_data.csv")
eng_stopwords = stopwords.words("english")

In [83]:
fake_news_df.head()

,title,text,date,fake_or_factual
0,HOLLYWEIRD LIB SUSAN SARANDON Compares Muslim ...,There are two small problems with your analogy...,"Dec 30, 2015",Fake News
1,Elijah Cummings Called Trump Out To His Face ...,Buried in Trump s bonkers interview with New Y...,"April 6, 2017",Fake News
2,Hillary Clinton Says Half Her Cabinet Will Be...,"Women make up over 50 percent of this country,...","April 26, 2016",Fake News
3,Russian bombing of U.S.-backed forces being di...,WASHINGTON (Reuters) - U.S. Defense Secretary ...,"September 18, 2017",Factual News
4,Britain says window to restore Northern Irelan...,BELFAST (Reuters) - Northern Ireland s politic...,"September 4, 2017",Factual News

In [84]:
def clean_fake_data(text):
    lower_case = text.lower()
    lower_case = re.sub(r"[^\w\s]", "", lower_case)
    tokens = word_tokenize(lower_case)
    return [lem.lemmatize(token) for token in tokens if token not in eng_stopwords]

In [85]:
fake_news_df["clean_text"] = fake_news_df["text"].apply(clean_fake_data)

In [86]:
fake_news_df.head()

,title,text,date,fake_or_factual,clean_text
0,HOLLYWEIRD LIB SUSAN SARANDON Compares Muslim ...,There are two small problems with your analogy...,"Dec 30, 2015",Fake News,"[two, small, problem, analogy, susan, jesus, m..."
1,Elijah Cummings Called Trump Out To His Face ...,Buried in Trump s bonkers interview with New Y...,"April 6, 2017",Fake News,"[buried, trump, bonkers, interview, new, york,..."
2,Hillary Clinton Says Half Her Cabinet Will Be...,"Women make up over 50 percent of this country,...","April 26, 2016",Fake News,"[woman, make, 50, percent, country, grossly, u..."
3,Russian bombing of U.S.-backed forces being di...,WASHINGTON (Reuters) - U.S. Defense Secretary ...,"September 18, 2017",Factual News,"[washington, reuters, u, defense, secretary, j..."
4,Britain says window to restore Northern Irelan...,BELFAST (Reuters) - Northern Ireland s politic...,"September 4, 2017",Factual News,"[belfast, reuters, northern, ireland, politica..."

In [87]:
fake_news_df["clean_text"][0]

['two',
 'small',
 'problem',
 'analogy',
 'susan',
 'jesus',
 'muslim',
 'joseph',
 'traveled',
 'bethlehem',
 'mary',
 'anyone',
 'paying',
 'attention',
 'appear',
 'many',
 'female',
 'refugee',
 'accompanying',
 'male',
 'muslim',
 'refugee',
 'greecesusan',
 'sarandon',
 'spent',
 'christmas',
 'holiday',
 'greek',
 'island',
 'lesbos',
 'assisting',
 'international',
 'organization',
 'mounting',
 'syrian',
 'refugee',
 'crisis',
 'crisis',
 'say',
 'recall',
 'travail',
 'joseph',
 'mary',
 'way',
 'inn',
 'bethlehemin',
 'column',
 'huffington',
 'post',
 'ryot',
 '69yearold',
 'oscarwinning',
 'actress',
 'described',
 'meeting',
 '16yearold',
 'girl',
 'apparently',
 'given',
 'birth',
 'shortly',
 'arriving',
 'island',
 'smile',
 'approach',
 'without',
 'translator',
 'conversation',
 'basicfriendly',
 'sarandon',
 'wrote',
 'experience',
 'take',
 'bundle',
 'next',
 'open',
 'inside',
 'perfect',
 'rosy',
 'newborn',
 'actress',
 'continuesshe',
 'beaming',
 'proud',
 'young',
 'girl',
 'given',
 'birth',
 'manage',
 'trip',
 'sea',
 'walking',
 'give',
 'birthwasn',
 'mary',
 'kid',
 'joseph',
 'took',
 'road',
 'far',
 'manger',
 'syrian',
 'baby',
 'room',
 'innsarandon',
 'short',
 'column',
 'part',
 'new',
 'collaborative',
 'series',
 'huffington',
 'post',
 'virtual',
 'reality',
 'network',
 'ryot',
 'called',
 'crossing',
 'see',
 'actress',
 'host',
 'series',
 'report',
 'chronicling',
 'refugee',
 'crisis',
 'unfolds',
 'greece',
 'actress',
 'also',
 'criticized',
 'political',
 'discourse',
 'surrounding',
 'refugee',
 'crisis',
 'united',
 'state',
 'seemed',
 'like',
 'people',
 'loudest',
 'voice',
 'xenophobic',
 'unamerican',
 'saidsarandon',
 'actor',
 'visited',
 'greek',
 'island',
 'assist',
 'international',
 'aid',
 'effort',
 'refugee',
 'homeland',
 'star',
 'mandy',
 'patinkin',
 'recently',
 'spent',
 'time',
 'assisting',
 'international',
 'rescue',
 'committee',
 'wrapping',
 'production',
 'fifth',
 'season',
 'hit',
 'showtime',
 'drama',
 'via',
 'breitbart',
 'news']

In [88]:
fake_news_df["fake"] = fake_news_df[fake_news_df["fake_or_factual"] == "Fake News"]["text"]

In [89]:
fake_news_df.head()

,title,text,date,fake_or_factual,clean_text,fake
0,HOLLYWEIRD LIB SUSAN SARANDON Compares Muslim ...,There are two small problems with your analogy...,"Dec 30, 2015",Fake News,"[two, small, problem, analogy, susan, jesus, m...",There are two small problems with your analogy...
1,Elijah Cummings Called Trump Out To His Face ...,Buried in Trump s bonkers interview with New Y...,"April 6, 2017",Fake News,"[buried, trump, bonkers, interview, new, york,...",Buried in Trump s bonkers interview with New Y...
2,Hillary Clinton Says Half Her Cabinet Will Be...,"Women make up over 50 percent of this country,...","April 26, 2016",Fake News,"[woman, make, 50, percent, country, grossly, u...","Women make up over 50 percent of this country,..."
3,Russian bombing of U.S.-backed forces being di...,WASHINGTON (Reuters) - U.S. Defense Secretary ...,"September 18, 2017",Factual News,"[washington, reuters, u, defense, secretary, j...",NaN
4,Britain says window to restore Northern Irelan...,BELFAST (Reuters) - Northern Ireland s politic...,"September 4, 2017",Factual News,"[belfast, reuters, northern, ireland, politica...",NaN

In [90]:
fake_news_df["fact"] = fake_news_df[fake_news_df["fake_or_factual"] == "Factual News"]["text"]

In [91]:
fake_news_df.head()

,title,text,date,fake_or_factual,clean_text,fake,fact
0,HOLLYWEIRD LIB SUSAN SARANDON Compares Muslim ...,There are two small problems with your analogy...,"Dec 30, 2015",Fake News,"[two, small, problem, analogy, susan, jesus, m...",There are two small problems with your analogy...,NaN
1,Elijah Cummings Called Trump Out To His Face ...,Buried in Trump s bonkers interview with New Y...,"April 6, 2017",Fake News,"[buried, trump, bonkers, interview, new, york,...",Buried in Trump s bonkers interview with New Y...,NaN
2,Hillary Clinton Says Half Her Cabinet Will Be...,"Women make up over 50 percent of this country,...","April 26, 2016",Fake News,"[woman, make, 50, percent, country, grossly, u...","Women make up over 50 percent of this country,...",NaN
3,Russian bombing of U.S.-backed forces being di...,WASHINGTON (Reuters) - U.S. Defense Secretary ...,"September 18, 2017",Factual News,"[washington, reuters, u, defense, secretary, j...",NaN,WASHINGTON (Reuters) - U.S. Defense Secretary ...
4,Britain says window to restore Northern Irelan...,BELFAST (Reuters) - Northern Ireland s politic...,"September 4, 2017",Factual News,"[belfast, reuters, northern, ireland, politica...",NaN,BELFAST (Reuters) - Northern Ireland s politic...

In [92]:
fake_news_df.drop(columns=["clean_text"], inplace=True)

In [93]:
fake_news_df.head()

,title,text,date,fake_or_factual,fake,fact
0,HOLLYWEIRD LIB SUSAN SARANDON Compares Muslim ...,There are two small problems with your analogy...,"Dec 30, 2015",Fake News,There are two small problems with your analogy...,NaN
1,Elijah Cummings Called Trump Out To His Face ...,Buried in Trump s bonkers interview with New Y...,"April 6, 2017",Fake News,Buried in Trump s bonkers interview with New Y...,NaN
2,Hillary Clinton Says Half Her Cabinet Will Be...,"Women make up over 50 percent of this country,...","April 26, 2016",Fake News,"Women make up over 50 percent of this country,...",NaN
3,Russian bombing of U.S.-backed forces being di...,WASHINGTON (Reuters) - U.S. Defense Secretary ...,"September 18, 2017",Factual News,NaN,WASHINGTON (Reuters) - U.S. Defense Secretary ...
4,Britain says window to restore Northern Irelan...,BELFAST (Reuters) - Northern Ireland s politic...,"September 4, 2017",Factual News,NaN,BELFAST (Reuters) - Northern Ireland s politic...

In [94]:
fake_str = "".join(fake_news_df[fake_news_df["fake_or_factual"] == "Fake News"]["text"].tolist())

In [95]:
fact_str = "".join(fake_news_df[fake_news_df["fake_or_factual"] == "Factual News"]["text"].tolist())
fact_str

'WASHINGTON (Reuters) - U.S. Defense Secretary Jim Mattis said on Monday that Russia s bombing of U.S-backed fighters in Syria was being discussed at the highest levels and while a communication link between the two countries had worked to avoid such incidents, the strike over the weekend was a departure.  When you look at the fact that this is a change, you can imagine this is at the highest levels,  Mattis told reporters. Russia s Defense Ministry on Sunday rejected the allegations, saying its planes only targeted Islamic State militants and that it had warned the United States well in advance of its operational plans. BELFAST (Reuters) - Northern Ireland s political parties are rapidly running out of time to restore a devolved power-sharing government, Britain s minister for the region said on Monday, as he sought to avoid a return of direct rule from London.  The window of opportunity to restore devolution and to form an executive is closing rapidly as we move further into the autumn and with pressures in public services already evident, the need for intervention is becoming increasingly clear,  James Brokenshire told a news conference.  I don t want to have to take this action, my intent is for politicians in Northern Ireland to form an executive. I m not going to pretend that this is easy as clear differences remain but it does remain achievable.   (Reuters) - Seattle financial worker Harrison Karlewicz had been considering joining an environmental activist group for a while. The day after Donald Trump won the White House, he signed up. “That was a big push for me, kind of a wakeup call,” the 25-year-old said, after joining 350 Seattle, a group that stages mass protests against fossil fuel use. “I thought, ‘I don’t feel involved. I want to get out there.’” During his campaign, Trump said global warming was a hoax and called for the Environmental Protection Agency to be gutted. He promised to “cancel” the Paris climate agreement between the United States and nearly 200 other countries to slow climate change, and he pledged to revive the coal industry. Karlewicz represents what environmental activists say is the silver lining of Trump’s electoral victory: Environmentally minded people angered by the outcome are rallying to their cause. At 350 Seattle, people packed a volunteer drop-in meeting  after news of Trump’s confirmed win, said organizer Emily Johnston. The group blocked a rail line in Washington state that transports oil to Shell and Tesoro refineries earlier this year.  \xa0\xa0\xa0\xa0“This was surprising to me, because I personally was so shaken that I felt practically paralyzed, and I know many other people did, too,” Johnston said. “The fact that many others responded by immediately engaging is incredibly heartening.” Jay O’Hara, a Vermont-based climate-change activist with the Climate Disobedience Center and a mastermind behind a coal shipment blockade in 2013 that spurred more radical fossil fuel activism, said Trump’s win represents an opportunity for environmentalists to focus on a clear enemy. “In some ways, it can almost be seen as a relief,” he said of Trump’s win. “We are going to have a real fight here, or maybe an actual argument.” Johnston, of 350 Seattle, who camped for a week at North Dakota’s Standing Rock Sioux reservation to protest pipeline construction, said that protesters would continue to take advantage of the vulnerability of energy infrastructure. “All these pipelines, all these tankers, all these trains have to go through thousands of miles” and could be potential protest targets, she said. Some of the well established national environmental organizations that helped draft the Obama administration’s environmental initiatives, like the Clean Power Plan to curb carbon dioxide emissions, will be shifting to a defensive posture under Trump’s leadership. “We’ll be in the Congress, in the courts, in the boardrooms and in the streets,” said Gene Karpinski, president of the Washington-based League of Conservation Voters, which backed Trump’s Democratic rival Hillary Clinton and spent over $45 million to support candidates in the 2016 elections. Karpinski said he expected legal action to prevent Trump from following through on his agenda.  Trump has appointed Myron Ebell, a known climate skeptic, to guide the reshaping of the EPA, and Trump energy adviser Kevin Cramer, a U.S. representative from North Dakota, said Trump is likely to target the Clean Power Plan and Waters of the United States rules during his first 100 days in office. Dan Farber, an environmental law professor at the University of California, Berkeley School of Law, said the best that advocates for climate change action could hope for from  courts is to “play successful defense against an anti-environmental onslaught” from the new administration. \xa0\xa0\xa0 “It’s a fairly grim situation,” he added. Several groups also said they would put a greater focus on state-level environmental initiatives to sidestep Trump’s administration.  The Sierra Club, which is headquartered in California, said it would push ahead with its Beyond Coal campaign, which has led to the retirement of hundreds of coal plants since it was launched more than a decade ago. The campaign mobilizes local activists and lawyers to push utilities and state regulators to shutter older plants and replace them with renewable energy.  “Clearly, we are going to have to fight and resist the worst impulses of the next administration,” said Michael Brune, Sierra Club’s executive director. “But we are also mindful that despite all odds, we were able to make great progress during the Bush administration and we hope to do it again.” BEIJING (Reuters) - U.S. President-elect Donald Trump’s call with Taiwan President Tsai Ing-wen was a “petty action” by Taiwan, Chinese Foreign Minister Wang Yi said on Saturday, Hong Kong-based Phoenix Television reported. The conversation was the first such contact with Taiwan by a U.S. president-elect or president since President Jimmy Carter switched diplomatic recognition from Taiwan to China in 1979, acknowledging Taiwan as part of “one China”. “This is just the Taiwan side engaging in a petty action, and cannot change the ‘one China’ structure already formed by the international community,” Wang said at an academic forum, the station said. “I believe that it won’t change the longstanding one China policy of the United States government. The ‘one China’ principle is the cornerstone of the healthy development of Sino-U.S. ties, and we hope this political basis is not interfered with or damaged in any way.” Defeated Nationalist forces fled to Taiwan at the end of a civil war with the Communists in 1949, and Beijing has never renounced the use of force to bring under its control what China views as a wayward province. Taiwan is one of China’s most sensitive policy issues, and China generally lambastes any form of official contact by foreign governments with Taiwan’s leaders. China is deeply suspicious of Tsai, who won election in January, and believes she wants to push for the island’s formal independence, a red line for Beijing. Tsai has said she wants to maintain the status quo with China and wants peaceful relations. QUEBEC CITY (Reuters) - U.S. Secretary of State John Kerry on Friday said he could not comment on private email chains of his predecessor Hillary Clinton, saying they were being withheld at the request of the U.S. intelligence community. “I can’t speak to the specifics of anything with respect to the technicalities, the contents ... because that’s not our job,” Kerry told a news conference in Canada. “We don’t know about it, it’s in other hands.” SAN FRANCISCO/WASHINGTON (Reuters) - President Donald Trump suffered another legal setback on Monday as a second federal appeals court refused to revive his travel ban on people entering the United States from six Muslim-majority nations in a dispute headed to the U.S. Supreme Court. The San Francisco-based 9th U.S. Circuit Court of Appeals  used narrow grounds to reject the Trump administration’s bid to undo a Hawaii federal judge’s decision blocking the temporary ban. It said the Republican president’s March 6 order violated existing immigration law. But the three-judge panel - all Democratic appointees - did not address whether it was unconstitutional discrimination against Muslims. A second court, the Richmond, Virginia-based 4th U.S. Circuit Court of Appeals, on May 25 upheld a Maryland judge’s ruling that also blocked Trump’s 90-day ban on travelers from Libya, Iran, Somalia, Sudan, Syria and Yemen.  The 4th Circuit had ruled that the ban, which replaced an earlier Jan. 27 one also blocked by the courts, “drips with religious intolerance, animus and discrimination” aimed at Muslims. The 9th Circuit largely left in place a nationwide injunction by Judge Derrick Watson that stopped parts of the order, which Trump said was urgently needed to prevent terrorism in the United States. That ruling came in a lawsuit challenging the order brought by the state of Hawaii, which stated the ban would harm its universities and tourism industry. Even before Monday’s ruling, the case was on the fast track to the Supreme Court, where the administration on June 1 filed an emergency request seeking to reinstate the order and hear its appeal of the 4th Circuit ruling. The Supreme Court could act on the administration’s request as soon as this week. Trump has been on the losing side in all four court rulings on the March order. White House spokesman Sean Spicer said the administration is reviewing Monday’s decision and expressed continued confidence that the order is fully lawful and ultimately will be upheld by the Supreme Court. “I think we can all attest that these are very dangerous times and we need every available tool at our disposal to prevent terrorists from entering the United States and committing acts of bloodshed and violence,” Spicer told a briefing. The 9th Circuit upheld the block on Trump’s three-month travel ban for the six countries and four-month suspension of all refugee admissions. But the court pared back part of Watson’s injunction in order to allow the government to conduct internal reviews on vetting procedures for these travelers. The administration said the travel ban was needed to allow time to implement stronger vetting measures, although it has already rolled out some new requirements not blocked by courts, including additional questions for visa applicants. Rather than focusing on Trump campaign statements as the Virginia-based court did, the 9th Circuit said the language in the executive order itself did not make a rational case for why a travel ban was needed. “The order does not offer a sufficient justification to suspend the entry of more than 180 million people on the basis of nationality,” the court wrote, referring the combined populations of the six countries.  Under immigration law, the administration was required to make findings that entry of the people in question would be detrimental to the United States but failed to do so, the court said. Stephen Vladeck, a professor at University of Texas School of Law, said the 9th Circuit provided an easier path for the Supreme Court to keep the travel ban on hold, because it avoided entirely the controversy over Trump’s campaign statements.  “It provides a very attractive way to leave the injunction in place without setting broader doctrinal rules about which they may have pause,” Vladeck said. Trump during the 2016 presidential campaign called for a “total and complete shutdown of Muslims entering the United States.” Monday was the deadline for the ban’s challengers to respond to the administration’s request that the order be allowed to go into effect. The American Civil Liberties Union, which represents people challenging the ban in the separate Maryland suit handled by the 4th Circuit, filed court papers urging the court not to take up the case, saying the order will become moot on Wednesday, 90 days from when Trump issued it. Lawyers for Hawaii called the order a “thinly veiled Muslim ban.” Trump’s earlier Jan. 27 order also included Iraq among the countries targeted and a total ban on refugees from Syria. The March order was intended to overcome the legal issues posed by the original ban, but was blocked before it could go into effect on March 16. The suits by Hawaii and the Maryland challengers argued that the order violated federal immigration law and a section of the Constitution’s First Amendment that prohibits the government from favoring or disfavoring any particular religion. Hawaii’s court papers mentioned a series of Trump Twitter posts on June 5. Trump described the order as a “watered down, politically correct” version of his original one. ANKARA (Reuters) - Turkey said on Monday its former economy minister, indicted in the United States for conspiring to violate U.S. sanctions on Iran, acted within international law and that charges against him amounted to a coup attempt through American courts. Former minister Zafer Caglayan  has protected Turkey s interests as Turkish economy minister, and has acted within the laws of our country and international laws while doing that,  government spokesman Bekir Bozdag said. The charges against Caglayan were  a repetition of the December FETO coup attempt ... through the American judiciary , Bozdag said, referring to 2013 leaks about alleged government corruption which were blamed on President Tayyip Erdogan s opponents. Caglayan and the ex-head of a state-owned Turkish bank were charged on Wednesday with conspiring to violate U.S. sanctions on Iran by illegally moving hundreds of millions of dollars through the U.S. financial system on Tehran s behalf. [nL8N1LO4RO] The charges stem from the case against Reza Zarrab, a wealthy Turkish-Iranian gold trader who was arrested in the United States over sanctions evasion last year. He has pleaded not guilty. Wednesday s indictment marked the first time an ex-government member with close ties to Erdogan had been charged in the investigation that has strained ties between Washington and Ankara.  Erdogan said last week he had told Washington that Turkey had never agreed to comply with its sanctions on Iran, and called on the United States to review the indictment. Turkey s presidency said on Saturday Erdogan spoke by phone with U.S. President Donald Trump. It did not say whether the two leaders discussed the case. [nL5N1LQ0HV] Bozdag also condemned the indictment of Erdogan s guards over violence during his visit to Washington in June, saying it relied on testimony from supporters of the outlawed militant PKK group, and had done  great damage  to U.S.-Turkish ties.WASHINGTON (Reuters) - U.S. President Donald Trump declined to say on Wednesday whether he will visit the Korean Peninsula’s demilitarized zone during an upcoming Asia tour. “I’d rather not say, but you’ll be surprised,” Trump told reporters on the White House South Lawn as he prepared to depart on a trip to Dallas.  Trump is scheduled to depart on Nov. 3 on a trip that includes visits to Japan, South Korea, China, Vietnam and the Philippines. His trip is expected to be heavily dominated by the nuclear and ballistic missile threat that North Korea poses. The DMZ is a border barrier between South and North Korea and is a traditional stop for American dignitaries. White House officials say Trump is to visit South Korea’s Camp Humphreys during his visit to South Korea to hail the U.S.-South Korean alliance.  There are no concerns about what message Trump would send by not going to the DMZ, a senior White House official told reporters on Monday. “The message is that we are guests during a state visit of President Moon Jae-in, who’s invited us to make a visit to Camp Humphreys. So we’ll keep talking with the South Korean government to see if there are things that they want to adjust,” the official said. WASHINGTON (Reuters) - The U.S. House of Representatives is expected to vote overwhelmingly on Tuesday for a bill that would slap new sanctions on Russia, Iran and North Korea, potentially complicating President Donald Trump’s hopes of pursuing improved relations with Moscow. The bipartisan measure aims to punish Russia for its 2014 annexation of Crimea from Ukraine and for alleged interference in the 2016 U.S. presidential election. The measure’s fate in the Senate is uncertain after a key senator said the deal announced over the weekend may not be final. Republican Senator Bob Corker, chairman of the Senate Foreign Relations Committee, told reporters that negotiators had a “very good weekend” but any announcement “seemed somewhat premature.” “We’re about there, there’s still some procedural issues we’re discussing but, you know, I think it worked out very, very well. We’ve still got a couple of things to talk about on North Korea,” Corker said. If the Republican-led Senate passes the measure, Trump will need to decide whether to sign the bill or veto it. Rejecting it would carry a risk that his veto could be overridden by lawmakers. The Trump administration has objected to a provision in the sanctions bill that the president obtain congressional approval before easing any sanctions on Moscow. “He’s going to study that legislation and see what the final product looks like,” White House spokeswoman Sarah Sanders told reporters on Monday, when asked whether Trump would support it. An earlier version of the bill, including sanctions on Russia and Iran, passed the Senate by 98-2 on June 15. A North Korea sanctions bill passed the House by 419-1 in May and House lawmakers were becoming increasingly impatient with the Senate’s failure to take up that legislation. House members saw the Iran and Russia sanctions bill as a chance to finally get the North Korea measure through the Senate. Trump’s relationship with Russia has been an issue during the first six months of his presidency as investigations continue into whether his associates colluded with Russian hackers to influence the election on his behalf. Russia denies interfering in the U.S. election. Trump has denied his campaign colluded with Moscow, calling the probes politically motivated and repeatedly criticizing them. In a series of tweets early on Tuesday, Trump lashed out at both U.S. Attorney General Jeff Sessions and Andrew McCabe, acting director of the Federal Bureau of Investigation. Without offering evidence, Trump cited “Ukrainian efforts to sabotage” his presidential campaign in order to aid his former Democratic rival, Hillary Clinton. Jared Kushner, Trump’s son-in-law and senior White House adviser, will visit Capitol Hill for a second straight day to be interviewed about his contacts with Russian officials during the 2016 campaign and the presidential transition. Trump on Tuesday praised Kushner, saying he had done “very well yesterday in proving he did not collude with the Russians.” GAZA (Reuters) - Rival Palestinian factions Fatah and Hamas agreed on Wednesday to delay final transfer of power of the Gaza Strip from Hamas to the Western-backed Palestinian government by 10 days to Dec. 10 to allow time to  complete arrangements , officials said. The factions signed a reconciliation deal brokered by Egypt last month after Hamas agreed to hand over administrative control of Gaza, including the key Rafah border crossing, a decade after seizing the enclave in a civil war. The deal bridges a bitter gulf between the Western-backed mainstream Fatah party of Palestinian President Mahmoud Abbas and Hamas, an Islamist movement designated as a terrorist group by Western countries and Israel. The agreement states that Hamas, which has disbanded its administration, would complete the handover by December 1 but disputes over the transfer process have emerged in recent days and Cairo has sent a senior security delegation to the territory to try to resolve the deadlock. In a brief joint statement, Fatah and 

In [96]:
def clean_data(text):
    lower_case = text.lower()
    lower_case = re.sub(r"[^\w\s]", "", lower_case)
    tokens = word_tokenize(lower_case)
    return [lem.lemmatize(token) for token in tokens if token not in eng_stopwords]


clean_fake_str = " ".join(clean_data(fake_str))
clean_fact_str = " ".join(clean_data(fact_str))

In [97]:
fake_nlp_doc = nlp(clean_fake_str)
fact_nlp_doc = nlp(clean_fact_str)

In [98]:
def getPOS(doc):
    pos_list = []    
    for word in doc:
        pos_list.append((word.text, word.pos_, word.ent_type_))
    return pos_list

In [99]:
fake_df = pd.DataFrame(getPOS(fake_nlp_doc), columns=['token', 'pos', 'ner'])
fact_df = pd.DataFrame(getPOS(fact_nlp_doc), columns=['token', 'pos', 'ner'])

In [100]:
fake_df.head(20)

           token    pos       ner
0            two    NUM  CARDINAL
1          small    ADJ
2        problem   NOUN
3        analogy   NOUN
4          susan  PROPN
5          jesus  PROPN    PERSON
6         muslim  PROPN    PERSON
7         joseph  PROPN    PERSON
8       traveled   VERB
9      bethlehem  PROPN       GPE
10          mary   VERB
11        anyone   PRON
12        paying   VERB
13     attention   NOUN
14        appear   VERB
15          many    ADJ
16        female    ADJ
17       refugee   NOUN
18  accompanying   VERB
19          male    ADJ

In [101]:
fact_df.head(20)

            token    pos       ner
0      washington  PROPN       GPE
1         reuters  PROPN
2               u  PROPN
3         defense  PROPN       ORG
4       secretary  PROPN
5             jim  PROPN    PERSON
6          mattis  PROPN    PERSON
7            said   VERB
8          monday  PROPN      DATE
9          russia  PROPN       GPE
10        bombing   NOUN
11       usbacked    ADJ
12        fighter   NOUN
13          syria  PROPN       GPE
14      discussed   VERB
15        highest    ADJ
16          level   NOUN
17  communication   NOUN
18           link   NOUN
19            two    NUM  CARDINAL

In [102]:
fact_df["ner"].value_counts()

ner
               16412
ORG              943
PERSON           872
DATE             842
GPE              719
NORP             360
CARDINAL         327
PERCENT           75
ORDINAL           58
LOC               49
QUANTITY          42
MONEY             35
TIME              23
FAC               12
EVENT              6
LAW                4
PRODUCT            2
WORK_OF_ART        2
LANGUAGE           1
Name: count, dtype: int64

In [103]:
fake_df["ner"].value_counts()

ner
               18460
PERSON          1100
ORG              606
DATE             604
GPE              385
CARDINAL         364
NORP             299
TIME              70
ORDINAL           62
PERCENT           31
LOC               20
MONEY             18
FAC               15
QUANTITY          13
WORK_OF_ART        6
EVENT              6
PRODUCT            6
LAW                1
Name: count, dtype: int64

In [104]:
fake_tokens = fake_df['token'].tolist()
fact_tokens = fact_df['token'].tolist()

In [105]:
fake_bi_grams = list(nltk.ngrams(fake_tokens, 2))
fact_bi_grams = list(nltk.ngrams(fact_tokens, 2))

In [106]:
fake_bi_grams

[('two', 'small'),
 ('small', 'problem'),
 ('problem', 'analogy'),
 ('analogy', 'susan'),
 ('susan', 'jesus'),
 ('jesus', 'muslim'),
 ('muslim', 'joseph'),
 ('joseph', 'traveled'),
 ('traveled', 'bethlehem'),
 ('bethlehem', 'mary'),
 ('mary', 'anyone'),
 ('anyone', 'paying'),
 ('paying', 'attention'),
 ('attention', 'appear'),
 ('appear', 'many'),
 ('many', 'female'),
 ('female', 'refugee'),
 ('refugee', 'accompanying'),
 ('accompanying', 'male'),
 ('male', 'muslim'),
 ('muslim', 'refugee'),
 ('refugee', 'greecesusan'),
 ('greecesusan', 'sarandon'),
 ('sarandon', 'spent'),
 ('spent', 'christmas'),
 ('christmas', 'holiday'),
 ('holiday', 'greek'),
 ('greek', 'island'),
 ('island', 'lesbos'),
 ('lesbos', 'assisting'),
 ('assisting', 'international'),
 ('international', 'organization'),
 ('organization', 'mounting'),
 ('mounting', 'syrian'),
 ('syrian', 'refugee'),
 ('refugee', 'crisis'),
 ('crisis', 'crisis'),
 ('crisis', 'say'),
 ('say', 'recall'),
 ('recall', 'travail'),
 ('travail', 'joseph'),
 ('joseph', 'mary'),
 ('mary', 'way'),
 ('way', 'inn'),
 ('inn', 'bethlehemin'),
 ('bethlehemin', 'column'),
 ('column', 'huffington'),
 ('huffington', 'post'),
 ('post', 'ryot'),
 ('ryot', '69yearold'),
 ('69yearold', 'oscarwinning'),
 ('oscarwinning', 'actress'),
 ('actress', 'described'),
 ('described', 'meeting'),
 ('meeting', '16yearold'),
 ('16yearold', 'girl'),
 ('girl', 'apparently'),
 ('apparently', 'given'),
 ('given', 'birth'),
 ('birth', 'shortly'),
 ('shortly', 'arriving'),
 ('arriving', 'island'),
 ('island', 'smile'),
 ('smile', 'approach'),
 ('approach', 'without'),
 ('without', 'translator'),
 ('translator', 'conversation'),
 ('conversation', 'basicfriendly'),
 ('basicfriendly', 'sarandon'),
 ('sarandon', 'wrote'),
 ('wrote', 'experience'),
 ('experience', 'take'),
 ('take', 'bundle'),
 ('bundle', 'next'),
 ('next', 'open'),
 ('open', 'inside'),
 ('inside', 'perfect'),
 ('perfect', 'rosy'),
 ('rosy', 'newborn'),
 ('newborn', 'actress'),
 ('actress', 'continuesshe'),
 ('continuesshe', 'beaming'),
 ('beaming', 'proud'),
 ('proud', 'young'),
 ('young', 'girl'),
 ('girl', 'given'),
 ('given', 'birth'),
 ('birth', 'manage'),
 ('manage', 'trip'),
 ('trip', 'sea'),
 ('sea', 'walking'),
 ('walking', 'give'),
 ('give', 'birthwasn'),
 ('birthwasn', 'mary'),
 ('mary', 'kid'),
 ('kid', 'joseph'),
 ('joseph', 'took'),
 ('took', 'road'),
 ('road', 'far'),
 ('far', 'manger'),
 ('manger', 'syrian'),
 ('syrian', 'baby'),
 ('baby', 'room'),
 ('room', 'innsarandon'),
 ('innsarandon', 'short'),
 ('short', 'column'),
 ('column', 'part'),
 ('part', 'new'),
 ('new', 'collaborative'),
 ('collaborative', 'series'),
 ('series', 'huffington'),
 ('huffington', 'post'),
 ('post', 'virtual'),
 ('virtual', 'reality'),
 ('reality', 'network'),
 ('network', 'ryot'),
 ('ryot', 'called'),
 ('called', 'crossing'),
 ('crossing', 'see'),
 ('see', 'actress'),
 ('actress', 'host'),
 ('host', 'series'),
 ('series', 'report'),
 ('report', 'chronicling'),
 ('chronicling', 'refugee'),
 ('refugee', 'crisis'),
 ('crisis', 'unfolds'),
 ('unfolds', 'greece'),
 ('greece', 'actress'),
 ('actress', 'also'),
 ('also', 'criticized'),
 ('criticized', 'political'),
 ('political', 'discourse'),
 ('discourse', 'surrounding'),
 ('surrounding', 'refugee'),
 ('refugee', 'crisis'),
 ('crisis', 'united'),
 ('united', 'state'),
 ('state', 'seemed'),
 ('seemed', 'like'),
 ('like', 'people'),
 ('people', 'loudest'),
 ('loudest', 'voice'),
 ('voice', 'xenophobic'),
 ('xenophobic', 'unamerican'),
 ('unamerican', 'saidsarandon'),
 ('saidsarandon', 'actor'),
 ('actor', 'visited'),
 ('visited', 'greek'),
 ('greek', 'island'),
 ('island', 'assist'),
 ('assist', 'international'),
 ('international', 'aid'),
 ('aid', 'effort'),
 ('effort', 'refugee'),
 ('refugee', 'homeland'),
 ('homeland', 'star'),
 ('star', 'mandy'),
 ('mandy', 'patinkin'),
 ('patinkin', 'recently'),
 ('recently', 'spent'),
 ('spent', 'time'),
 ('time', 'assisting'),
 ('assisting', 'international'),
 ('international', 'rescue'),
 ('rescue', 'committee'),
 ('committee', 'wrapping'),
 ('wrapping', 'production'),
 ('production', 'fifth'),
 ('fifth', 'season'),
 ('season', 'hit'),
 ('hit', 'showtime'),
 ('showtime', 'drama'),
 ('drama', 'via'),
 ('via', 'breitbart'),
 ('breitbart', 'newsburied'),
 ('newsburied', 'trump'),
 ('trump', 'bonkers'),
 ('bonkers', 'interview'),
 ('interview', 'new'),
 ('new', 'york'),
 ('york', 'time'),
 ('time', 'reporter'),
 ('reporter', 'maggie'),
 ('maggie', 'haberman'),
 ('haberman', 'glenn'),
 ('glenn', 'thrush'),
 ('thrush', 'outrageous'),
 ('outrageous', 'exchange'),
 ('exchange', 'trump'),
 ('trump', 'claim'),
 ('claim', 'happened'),
 ('happened', 'recentlytrump'),
 ('recentlytrump', 'u'),
 ('u', 'representative'),
 ('representative', 'elijah'),
 ('elijah', 'cummings'),
 ('cummings', 'office'),
 ('office', 'said'),
 ('said', 'go'),
 ('go', 'one'),
 ('one', 'great'),
 ('great', 'president'),
 ('president', 'history'),
 ('history', 'country'),
 ('country', 'haberman'),
 ('haberman', 'reallytrump'),
 ('reallytrump', 'went'),
 ('went', 'watched'),
 ('watched', 'television'),
 ('television', 'yesterday'),
 ('yesterday', 'said'),
 ('said', 'man'),
 ('man', 'would'),
 ('would', 'odd'),
 ('odd', 'considering'),
 ('considering', 'cummings'),
 ('cummings', 'fiery'),
 ('fiery', 'democratic'),
 ('democratic', 'congressman'),
 ('congressman', 'one'),
 ('one', 'trump'),
 ('trump', 'intense'),
 ('intense', 'critic'),
 ('critic', 'public'),
 ('public', 'cummings'),
 ('cummings', 'outspoken'),
 ('outspoken', 'trump'),
 ('trump', 'disturbing'),
 ('disturbing', 'connection'),
 ('connection', 'russia'),
 ('russia', 'gop'),
 ('gop', 'botched'),
 ('botched', 'attempt'),
 ('attempt', 'cover'),
 ('cover', 'connection'),
 ('connection', 'repeatedly'),
 ('repeatedly', 'demanded'),
 ('demanded', 'trump'),
 ('trump', 'divest'),
 ('divest', 'numerous'),
 ('numerous', 'conflict'),
 ('conflict', 'interest'),
 ('interest', 'hardly'),
 ('hardly', 'sound'),
 ('sound', 'like'),
 ('like', 'person'),
 ('person', 'looked'),
 ('looked', 'trump'),
 ('trump', 'trainwreck'),
 ('trainwreck', 'first'),
 ('first', 'three'),
 ('three', 'month'),
 ('month', 'office'),
 ('office', 'concluded'),
 ('concluded', 'deserves'),
 ('deserves', 'mount'),
 ('mount', 'rushmoreone'),
 ('rushmoreone', 'theory'),
 ('theory', 'trump'),
 ('trump', 'flatly'),
 ('flatly', 'lied'),
 ('lied', 'always'),
 ('always', 'possibility'),
 ('possibility', 'trump'),
 ('trump', 'pathological'),
 ('pathological', 'liar'),
 ('liar', 'another'),
 ('another', 'suggested'),
 ('suggested', 'writer'),
 ('writer', 'jamelle'),
 ('jamelle', 'bouie'),
 ('bouie', 'trump'),
 ('trump', 'mixed'),
 ('mixed', 'two'),
 ('two', 'black'),
 ('black', 'men'),
 ('men', 'conflating'),
 ('conflating', 'cummings'),
 ('cummings', 'guy'),
 ('guy', 'another'),
 ('another', 'strong'),
 ('strong', 'possibility'),
 ('possibility', 'trump'),
 ('trump', 'shown'),
 ('shown', 'complete'),
 ('complete', 'lack'),
 ('lack', 'interest'),
 ('interest', 'life'),
 ('life', 'black'),
 ('black', 'americansfortunately'),
 ('americansfortunately', 'cummings'),
 ('cummings', 'came'),
 ('came', 'provide'),
 ('provide', 'real'),
 ('real', 'answer'),
 ('answer', 'trump'),
 ('trump', 'took'),
 ('took', 'criticism'),
 ('criticism', 'cummings'),
 ('cummings', 'made'),
 ('made', 'face'),
 ('face', 'filtered'),
 ('filtered', 'unchecked'),
 ('unchecked', 'narcissism'),
 ('narcissism', 'cummings'),
 ('cummings', 'describes'),
 ('describes', 'meeting'),
 ('meeting', 'trump'),
 ('trump', 'said'),
 ('said', 'praising'),
 ('praising', 'meeting'),
 ('meeting', 'president'),
 ('president', 'several'),
 ('several', 'occasion'),
 ('occasion', 'since'),
 ('since', 'said'),
 ('said', 'repeatedly'),
 ('repeatedly', 'could'),
 ('could', 'great'),
 ('great', 'president'),
 ('president', 'take'),
 ('take', 'step'),
 ('step', 'truly'),
 ('truly', 'represent'),
 ('represent', 'american'),
 ('american', 'rather'),
 ('rather', 'continuing'),
 ('continuing', 'divisive'),
 ('divisive', 'harmful'),
 ('harmful', 'path'),
 ('path', 'currently'),
 ('currently', 'note'),
 ('note', 'jab'),
 ('jab', 'trump'),
 ('trump', 'completely'),
 ('completely', 'missed'),
 ('missed', 'trump'),
 ('trump', 'stop'),
 ('stop', 'divisive'),
 ('divisive', 'harmful'),
 ('harmful', 'could'),
 ('could', 'someday'),
 ('someday', 'great'),
 ('great', 'president'),
 ('president', 'far'),
 ('far', 'done'),
 ('done', 'even'),
 ('even', 'tried'),
 ('tried', 'underscore'),
 ('underscore', 'little'),
 ('little', 'trump'),
 ('trump', 'tried'),
 ('tried', 'stop'),
 ('stop', 'divisive'),
 ('divisive', 'interview'),
 ('interview', 'defended'),
 ('defended', 'bill'),
 ('bill', 'reilly'),
 ('reilly', 'sexually'),
 ('sexually', 'harassing'),
 ('harassing', 'woman'),
 ('woman', 'fox'),
 ('fox', 'newsunintentionally'),
 ('newsunintentionally', 'trump'),
 ('trump', 'bizarre'),
 ('bizarre', 'retelling'),
 ('retelling', 'went'),
 ('went', 'meeting'),
 ('meeting', 'cummings'),
 ('cummings', 'exemplifies'),
 ('exemplifies', 'warped'),
 ('warped', 'way'),
 ('way', 'trump'),
 ('trump', 'see'),
 ('see', 'world'),
 ('world', 'criticism'),
 ('criticism', 'turn'),
 ('turn', 'praise'),
 ('praise', 'stripping'),
 ('stripping', 'away'),
 ('away', 'context'),
 ('context', 'process'),
 ('process', 'may'),
 ('may', 'explain'),
 ('explain', 'example'),
 ('example', 'trump'),
 ('trump', 'seems'),
 ('seems', 'genuinely'),
 ('genuinely', 'believe'),
 ('believe', 'saw'),
 ('saw', 'muslim'),
 ('muslim', 'american'),
 ('american', 'celebrating'),
 ('celebrating', '911'),
 ('911', 'ego'),
 ('ego', 'filter'),
 ('filter', 'everything'),
 ('everything', 'fact'),
 ('fact', 'get'),
 ('get', 'distorted'),
 ('distorted', 'retooled'),
 ('retooled', 'agendathe'),
 ('agendathe', 'fact'),
 ('fact', 'president'),
 ('president', 'seem'),
 ('seem', 'understand'),
 ('understand', 'difference'),
 ('difference', 'reality'),
 ('reality', 'fantasy'),
 ('fantasy', 'world'),
 ('world', 'exists'),
 ('exists', 'head'),
 ('head', 'recipe'),
 ('recipe', 'disaster'),
 ('disaster', 'meeting'),
 ('meeting', 'congressman'),
 ('congressman', 'get'),
 ('get', 'distorted'),
 ('distorted', 'delusion'),
 ('delusion', 'trump'),
 ('trump', 'living'),
 ('living', 'infeatured'),
 ('infeatured', 'image'),
 ('image', 'via'),
 ('via', 'win'),
 ('win', 'mcnameegetty'),
 ('mcnameegetty', 'imageswomen'),
 ('imageswomen', 'make'),
 ('make', '50'),
 ('50', 'percent'),
 ('percent', 'country'),
 ('country', 'grossly'),
 ('grossly', 'underrepresented'),
 ('underrepresented', 'everything'),
 ('everything', 'united'),
 ('united', 'state'),
 ('state', 'congress'),
 ('congress', '80'),
 ('80', 'percent'),
 ('percent', 'representing'),
 ('representing', 'people'),
 ('people', 'men'),
 ('men', '80'),
 ('80', 'percent'),
 ('percent', 'senate'),
 ('senate', '81'),
 ('81', 'percent'),
 ('percent', 'houseon'),
 ('houseon', 'supreme'),
 ('supreme', 'court'),
 ('court', 'three'),
 ('three', 'nine'),
 ('nine', 'justice'),
 ('justice', 'womenand'),
 ('womenand', 'yes'),
 ('yes', 'even'),
 ('even', 'progressive'),
 ('progressive', 'obama'),
 ('obama', 'administration'),
 ('administration', '13'),
 ('13', '47'),
 ('47', 'individual'),
 ('individual', 'served'),
 ('served', 'cabinet'),
 ('cabinet', 'woman'),
 ('woman', '28'),
 ('28', 'percentit'),
 ('percentit', 'secret'),
 ('secret', 'washington'),
 ('washington', 'dc'),
 ('dc', 'still'),
 ('still', 'hard'),
 ('hard', 'place'),
 ('place', 'woman'),
 ('woman', 'find'),
 ('find', 'voice'),
 ('voice', 'even'),
 ('even', 'though'),
 ('though', 'proven'),
 ('proven', 'statistically'),
 ('statistically', 'woman'),
 ('woman', 'take'),
 ('take', 'charge'),
 ('charge', 'operation'),
 ('operation', 'debate'),
 ('debate', 'dc'),
 ('dc', 'stuff'),
 ('stuff', 'get'),
 ('get', 'done'),
 ('done', 'quicker'),
 ('quicker', 'bipartisan'),
 ('bipartisan', 'manner'),
 ('manner', 'still'),
 ('still', 'woman'),
 ('woman', 'taken'),
 ('taken', 'seriouslybut'),
 ('seriouslybut', 'hillary'),
 ('hillary', 'clinton'),
 ('clinton', 'shattering'),
 ('shattering', 'glass'),
 ('glass', 'ceiling'),
 ('ceiling', 'want'),
 ('want', 'shatter'),
 ('shatter', 'aspect'),
 ('aspect', 'dc'),
 ('dc', 'starting'),
 ('starting', 'cabinet'),
 ('cabinet', 'win'),
 ('win', 'presidencyin'),
 ('presidencyin', 'msnbc'),
 ('msnbc', 'town'),
 ('town', 'hall'),
 ('hall', 'monday'),
 ('monday', 'night'),
 ('night', 'clinton'),
 ('clinton', 'told'),
 ('told', 'viewer'),
 ('viewer', 'intends'),
 ('intends', 'cabinet'),
 ('cabinet', 'reflect'),
 ('reflect', 'demographic'),
 ('demographic', 'americawell'),
 ('americawell', 'going'),
 ('going', 'cabinet'),
 ('cabinet', 'look'),
 ('look', 'like'),
 ('like', 'america'),
 ('america', '50'),
 ('50', 'percent'),
 ('percent', 'america'),
 ('america', 'woman'),
 ('woman', 'whether'),
 ('whether', 'vice'),
 ('vice', 'president'),
 ('president', 'member'),
 ('member', 'cabinet'),
 ('cabinet', 'white'),
 ('white', 'house'),
 ('house', 'staff'),
 ('staff', 'want'),
 ('want', 'broad'),
 ('broad', 'set'),
 ('set', 'experience'),
 ('experience', 'possibly'),
 ('possibly', 'draw'),
 ('draw', 'together'),
 ('together', 'someone'),
 ('someone', 'like'),
 ('like', 'listen'),
 ('listen', 'people'),
 ('people', 'come'),
 ('come', 'problem'),
 ('problem', 'different'),
 ('different', 'perspectiveswhile'),
 ('perspectiveswhile', 'donald'),
 ('donald', 'trump'),
 ('trump', 'accuses'),
 ('accuses', 'playing'),
 ('playing', 'woman'),
 ('woman', 'card'),
 ('card', 'clinton'),
 ('clinton', 'setting'),
 ('setting', 'motion'),
 ('motion', 'push'),
 ('push', 'make'),
 ('make', 'woman'),
 ('woman', 'equally'),
 ('equally', 'represented'),
 ('represented', 'american'),
 ('american', 'society'),
 ('society', 'something'),
 ('something', 'trump'),
 ('trump', 'would'),
 ('would', 'never'),
 ('never', 'considershould'),
 ('considershould', 'clinton'),
 ('clinton', 'win'),
 ('win', 'responsible'),
 ('responsible', 'cabinet'),
 ('cabinet', 'also'),
 ('also', 'appointment'),
 ('appointment', 'supreme'),
 ('supreme', 'court'),
 ('court', 'could'),
 ('could', 'produce'),
 ('produce', 'two'),
 ('two', 'vacancy'),
 ('vacancy', 'next'),
 ('next', 'four'),
 ('four', 'yearsbut'),
 ('yearsbut', 'particular'),
 ('particular', 'election'),
 ('election', 'could'),
 ('could', 'driving'),
 ('driving', 'force'),
 ('force', 'woman'),
 ('woman', 'congress'),
 ('congress', 'democrat'),
 ('democrat', 'opportunity'),
 ('opportunity', 'get'),
 ('get', 'elect'),
 ('elect', 'woman'),
 ('woman', 'california'),
 ('california', 'maryland'),
 ('maryland', 'new'),
 ('new', 'york'),
 ('york', 'floridaif'),
 ('floridaif', 'woman'),
 ('woman', 'fifty'),
 ('fifty', 'percent'),
 ('percent', 'population'),
 ('population', 'deserve'),
 ('deserve', 'equal'),
 ('equal', 'representation'),
 ('representation', 'every'),
 ('every', 'level'),
 ('level', 'clinton'),
 ('clinton', 'seems'),
 ('seems', 'definitely'),
 ('definitely', 'board'),
 ('board', 'making'),
 ('making', 'sure'),
 ('sure', 'happens'),
 ('happens', 'become'),
 ('become', 'presidentfeatured'),
 ('presidentfeatured', 'image'),
 ('image', 'via'),
 ('via', 'justin'),
 ('justin', 'sullivangetty'),
 ('sullivangetty', 'imagesshame'),
 ('imagesshame', 'teen'),
 ('teen', 'vogue'),
 ('vogue', 'maxine'),
 ('maxine', 'water'),
 ('water', 'guest'),
 ('guest', 'teen'),
 ('teen', 'vogue'),
 ('vogue', 'interviewed'),
 ('interviewed', 'calling'),
 ('calling', 'young'),
 ('young', 'teen'),
 ('teen', 'resist'),
 ('resist', 'president'),
 ('president', 'sick'),
 ('sick', 'behavior'),
 ('behavior', 'grown'),
 ('grown', 'woman'),
 ('woman', 'smell'),
 ('smell', 'like'),
 ('like', 'sedition'),
 ('sedition', 'read'),
 ('read', 'answer'),
 ('answer', 'question'),
 ('question', 'belowteen'),
 ('belowteen', 'vote'),
 ('vote', 'asked'),
 ('asked', 'advice'),
 ('advice', 'would'),
 ('would', 'give'),
 ('give', 'burgeoning'),
 ('burgeoning', 'young'),
 ('young', 'activist'),
 ('activist', 'want'),
 ('want', 'help'),
 ('help', 'resist'),
 ('resist', 'movement'),
 ('movement', 'create'),
 ('create', 'effective'),
 ('effective', 'political'),
 ('political', 'change'),
 ('change', 'citizen'),
 ('citizen', 'help'),
 ('help', 'congresswoman'),
 ('congresswoman', 'achieve'),
 ('achieve', 'changemw'),
 ('changemw', 'several'),
 ('several', 'thing'),
 ('thing', 'done'),
 ('done', 'love'),
 ('love', 'dominate'),
 ('dominate', 'social'),
 ('social', 'medium'),
 ('medium', 'way'),
 ('way', 'communicate'),
 ('communicate', 'people'),
 ('people', 'sharing'),
 ('sharing', 'retweet'),
 ('retweet', 'every'),
 ('every', 'time'),
 ('time', 'bring'),
 ('bring', 'another'),
 ('another', 'person'),
 ('person', 'listen'),
 ('listen', 'read'),
 ('read', 'going'),
 ('going', 'gain'),
 ('gain', 'another'),
 ('another', 'supporter'),
 ('supporter', 'continue'),
 ('continue', 'speak'),
 ('speak', 'convince'),
 ('convince', 'people'),
 ('people', 'bring'),
 ('bring', 'president'),
 ('president', 'know'),
 ('know', 'become'),
 ('become', 'voter'),
 ('voter', 'going'),
 ('going', 'vote'),
 ('vote', 'investment'),
 ('investment', 'political'),
 ('political', 'process'),
 ('process', 'bring'),
 ('bring', 'president'),
 ('president', 'congresswoman'),
 ('congresswoman', 'maxine'),
 ('maxine', 'water'),
 ('water', 'desperate'),
 ('desperate', 'impeach'),
 ('impeach', '45'),
 ('45', 'pleading'),
 ('pleading', 'teenager'),
 ('teenager', 'follow'),
 ('follow', 'example'),
 ('example', 'push'),
 ('push', 'political'),
 ('political', 'agenda'),
 ('agenda', 'church'),
 ('church', 'everywhere'),
 ('everywhere', 'elsewaters'),
 ('elsewaters', 'led'),
 ('led', 'chant'),
 ('chant', 'impeach'),
 ('impeach', '45'),
 ('45', 'rally'),
 ('rally', 'cry'),
 ('cry', 'unseat'),
 ('unseat', 'president'),
 ('president', 'trump'),
 ('trump', 'teen'),
 ('teen', 'vogue'),
 ('vogue', 'summit'),
 ('summit', 'los'),
 ('los', 'angeles'),
 ('angeles', 'last'),
 ('last', 'weekend'),
 ('weekend', 'urging'),
 ('urging', 'mostly'),
 ('mostly', 'teenage'),
 ('teenage', 'female'),
 ('female', 'crowd'),
 ('crowd', 'take'),
 ('take', 'cause'),
 ('cause', 'repeat'),
 ('repeat', 'mantra'),
 ('mantra', 'everywhere'),
 ('everywhere', 'go'),
 ('go', 'impeach'),
 ('impeach', '45'),
 ('45', 'right'),
 ('right', 'water'),
 ('water', 'said'),
 ('said', 'let'),
 ('let', 'sing'),
 ('sing', 'song'),
 ('song', 'country'),
 ('country', 'wherever'),
 ('wherever', 'let'),
 ('let', 'talk'),
 ('talk', 'workplace'),
 ('workplace', 'let'),
 ('let', 'talk'),
 ('talk', 'church'),
 ('church', 'let'),
 ('let', 'talk'),
 ('talk', 'organized'),
 ('organized', 'labor'),
 ('labor', 'let'),
 ('let', 'get'),
 ('get', 'people'),
 ('people', 'coming'),
 ('coming', 'forefront'),
 ('forefront', 'water'),
 ('water', '79'),
 ('79', 'apparently'),
 ('apparently', 'belief'),
 ('belief', 'mob'),
 ('mob', 'young'),
 ('young', 'girl'),
 ('girl', 'many'),
 ('many', 'old'),
 ('old', 'enough'),
 ('enough', 'vote'),
 ('vote', 'chanting'),
 ('chanting', 'impeach'),
 ('impeach', '45'),
 ('45', 'convince'),
 ('convince', 'republican'),
 ('republican', 'lawmaker'),
 ('lawmaker', 'reverse'),
 ('reverse', 'course'),
 ('course', 'plan'),
 ('plan', 'lower'),
 ('lower', 'tax'),
 ('tax', 'american'),
 ('american', 'remove'),
 ('remove', 'president'),
 ('president', 'partyso'),
 ('partyso', 'far'),
 ('far', 'water'),
 ('water', 'call'),
 ('call', 'colleague'),
 ('colleague', 'congress'),
 ('congress', 'impeach'),
 ('impeach', 'trump'),
 ('trump', 'fallen'),
 ('fallen', 'deaf'),
 ('deaf', 'ear'),
 ('ear', 'lawmaker'),
 ('lawmaker', 'voted'),
 ('voted', '36458'),
 ('36458', 'resolution'),
 ('resolution', 'consider'),
 ('consider', 'move'),
 ('move', 'week'),
 ('week', 'fox'),
 ('fox', 'news'),
 ('news', 'reportsread'),
 ('reportsread', 'american'),
 ('american', 'mirrorformer'),
 ('mirrorformer', 'white'),
 ('white', 'house'),
 ('house', 'press'),
 ('press', 'secretary'),
 ('secretary', 'obama'),
 ('obama', 'administration'),
 ('administration', 'jay'),
 ('jay', 'carney'),

In [107]:
fact_bi_grams

[('washington', 'reuters'),
 ('reuters', 'u'),
 ('u', 'defense'),
 ('defense', 'secretary'),
 ('secretary', 'jim'),
 ('jim', 'mattis'),
 ('mattis', 'said'),
 ('said', 'monday'),
 ('monday', 'russia'),
 ('russia', 'bombing'),
 ('bombing', 'usbacked'),
 ('usbacked', 'fighter'),
 ('fighter', 'syria'),
 ('syria', 'discussed'),
 ('discussed', 'highest'),
 ('highest', 'level'),
 ('level', 'communication'),
 ('communication', 'link'),
 ('link', 'two'),
 ('two', 'country'),
 ('country', 'worked'),
 ('worked', 'avoid'),
 ('avoid', 'incident'),
 ('incident', 'strike'),
 ('strike', 'weekend'),
 ('weekend', 'departure'),
 ('departure', 'look'),
 ('look', 'fact'),
 ('fact', 'change'),
 ('change', 'imagine'),
 ('imagine', 'highest'),
 ('highest', 'level'),
 ('level', 'mattis'),
 ('mattis', 'told'),
 ('told', 'reporter'),
 ('reporter', 'russia'),
 ('russia', 'defense'),
 ('defense', 'ministry'),
 ('ministry', 'sunday'),
 ('sunday', 'rejected'),
 ('rejected', 'allegation'),
 ('allegation', 'saying'),
 ('saying', 'plane'),
 ('plane', 'targeted'),
 ('targeted', 'islamic'),
 ('islamic', 'state'),
 ('state', 'militant'),
 ('militant', 'warned'),
 ('warned', 'united'),
 ('united', 'state'),
 ('state', 'well'),
 ('well', 'advance'),
 ('advance', 'operational'),
 ('operational', 'plan'),
 ('plan', 'belfast'),
 ('belfast', 'reuters'),
 ('reuters', 'northern'),
 ('northern', 'ireland'),
 ('ireland', 'political'),
 ('political', 'party'),
 ('party', 'rapidly'),
 ('rapidly', 'running'),
 ('running', 'time'),
 ('time', 'restore'),
 ('restore', 'devolved'),
 ('devolved', 'powersharing'),
 ('powersharing', 'government'),
 ('government', 'britain'),
 ('britain', 'minister'),
 ('minister', 'region'),
 ('region', 'said'),
 ('said', 'monday'),
 ('monday', 'sought'),
 ('sought', 'avoid'),
 ('avoid', 'return'),
 ('return', 'direct'),
 ('direct', 'rule'),
 ('rule', 'london'),
 ('london', 'window'),
 ('window', 'opportunity'),
 ('opportunity', 'restore'),
 ('restore', 'devolution'),
 ('devolution', 'form'),
 ('form', 'executive'),
 ('executive', 'closing'),
 ('closing', 'rapidly'),
 ('rapidly', 'move'),
 ('move', 'autumn'),
 ('autumn', 'pressure'),
 ('pressure', 'public'),
 ('public', 'service'),
 ('service', 'already'),
 ('already', 'evident'),
 ('evident', 'need'),
 ('need', 'intervention'),
 ('intervention', 'becoming'),
 ('becoming', 'increasingly'),
 ('increasingly', 'clear'),
 ('clear', 'james'),
 ('james', 'brokenshire'),
 ('brokenshire', 'told'),
 ('told', 'news'),
 ('news', 'conference'),
 ('conference', 'want'),
 ('want', 'take'),
 ('take', 'action'),
 ('action', 'intent'),
 ('intent', 'politician'),
 ('politician', 'northern'),
 ('northern', 'ireland'),
 ('ireland', 'form'),
 ('form', 'executive'),
 ('executive', 'going'),
 ('going', 'pretend'),
 ('pretend', 'easy'),
 ('easy', 'clear'),
 ('clear', 'difference'),
 ('difference', 'remain'),
 ('remain', 'remain'),
 ('remain', 'achievable'),
 ('achievable', 'reuters'),
 ('reuters', 'seattle'),
 ('seattle', 'financial'),
 ('financial', 'worker'),
 ('worker', 'harrison'),
 ('harrison', 'karlewicz'),
 ('karlewicz', 'considering'),
 ('considering', 'joining'),
 ('joining', 'environmental'),
 ('environmental', 'activist'),
 ('activist', 'group'),
 ('group', 'day'),
 ('day', 'donald'),
 ('donald', 'trump'),
 ('trump', 'white'),
 ('white', 'house'),
 ('house', 'signed'),
 ('signed', 'big'),
 ('big', 'push'),
 ('push', 'kind'),
 ('kind', 'wakeup'),
 ('wakeup', 'call'),
 ('call', '25yearold'),
 ('25yearold', 'said'),
 ('said', 'joining'),
 ('joining', '350'),
 ('350', 'seattle'),
 ('seattle', 'group'),
 ('group', 'stage'),
 ('stage', 'mass'),
 ('mass', 'protest'),
 ('protest', 'fossil'),
 ('fossil', 'fuel'),
 ('fuel', 'use'),
 ('use', 'thought'),
 ('thought', 'do'),
 ('do', 'nt'),
 ('nt', 'feel'),
 ('feel', 'involved'),
 ('involved', 'want'),
 ('want', 'get'),
 ('get', 'campaign'),
 ('campaign', 'trump'),
 ('trump', 'said'),
 ('said', 'global'),
 ('global', 'warming'),
 ('warming', 'hoax'),
 ('hoax', 'called'),
 ('called', 'environmental'),
 ('environmental', 'protection'),
 ('protection', 'agency'),
 ('agency', 'gutted'),
 ('gutted', 'promised'),
 ('promised', 'cancel'),
 ('cancel', 'paris'),
 ('paris', 'climate'),
 ('climate', 'agreement'),
 ('agreement', 'united'),
 ('united', 'state'),
 ('state', 'nearly'),
 ('nearly', '200'),
 ('200', 'country'),
 ('country', 'slow'),
 ('slow', 'climate'),
 ('climate', 'change'),
 ('change', 'pledged'),
 ('pledged', 'revive'),
 ('revive', 'coal'),
 ('coal', 'industry'),
 ('industry', 'karlewicz'),
 ('karlewicz', 'represents'),
 ('represents', 'environmental'),
 ('environmental', 'activist'),
 ('activist', 'say'),
 ('say', 'silver'),
 ('silver', 'lining'),
 ('lining', 'trump'),
 ('trump', 'electoral'),
 ('electoral', 'victory'),
 ('victory', 'environmentally'),
 ('environmentally', 'minded'),
 ('minded', 'people'),
 ('people', 'angered'),
 ('angered', 'outcome'),
 ('outcome', 'rallying'),
 ('rallying', 'cause'),
 ('cause', '350'),
 ('350', 'seattle'),
 ('seattle', 'people'),
 ('people', 'packed'),
 ('packed', 'volunteer'),
 ('volunteer', 'dropin'),
 ('dropin', 'meeting'),
 ('meeting', 'news'),
 ('news', 'trump'),
 ('trump', 'confirmed'),
 ('confirmed', 'win'),
 ('win', 'said'),
 ('said', 'organizer'),
 ('organizer', 'emily'),
 ('emily', 'johnston'),
 ('johnston', 'group'),
 ('group', 'blocked'),
 ('blocked', 'rail'),
 ('rail', 'line'),
 ('line', 'washington'),
 ('washington', 'state'),
 ('state', 'transport'),
 ('transport', 'oil'),
 ('oil', 'shell'),
 ('shell', 'tesoro'),
 ('tesoro', 'refinery'),
 ('refinery', 'earlier'),
 ('earlier', 'year'),
 ('year', 'surprising'),
 ('surprising', 'personally'),
 ('personally', 'shaken'),
 ('shaken', 'felt'),
 ('felt', 'practically'),
 ('practically', 'paralyzed'),
 ('paralyzed', 'know'),
 ('know', 'many'),
 ('many', 'people'),
 ('people', 'johnston'),
 ('johnston', 'said'),
 ('said', 'fact'),
 ('fact', 'many'),
 ('many', 'others'),
 ('others', 'responded'),
 ('responded', 'immediately'),
 ('immediately', 'engaging'),
 ('engaging', 'incredibly'),
 ('incredibly', 'heartening'),
 ('heartening', 'jay'),
 ('jay', 'ohara'),
 ('ohara', 'vermontbased'),
 ('vermontbased', 'climatechange'),
 ('climatechange', 'activist'),
 ('activist', 'climate'),
 ('climate', 'disobedience'),
 ('disobedience', 'center'),
 ('center', 'mastermind'),
 ('mastermind', 'behind'),
 ('behind', 'coal'),
 ('coal', 'shipment'),
 ('shipment', 'blockade'),
 ('blockade', '2013'),
 ('2013', 'spurred'),
 ('spurred', 'radical'),
 ('radical', 'fossil'),
 ('fossil', 'fuel'),
 ('fuel', 'activism'),
 ('activism', 'said'),
 ('said', 'trump'),
 ('trump', 'win'),
 ('win', 'represents'),
 ('represents', 'opportunity'),
 ('opportunity', 'environmentalist'),
 ('environmentalist', 'focus'),
 ('focus', 'clear'),
 ('clear', 'enemy'),
 ('enemy', 'way'),
 ('way', 'almost'),
 ('almost', 'seen'),
 ('seen', 'relief'),
 ('relief', 'said'),
 ('said', 'trump'),
 ('trump', 'win'),
 ('win', 'going'),
 ('going', 'real'),
 ('real', 'fight'),
 ('fight', 'maybe'),
 ('maybe', 'actual'),
 ('actual', 'argument'),
 ('argument', 'johnston'),
 ('johnston', '350'),
 ('350', 'seattle'),
 ('seattle', 'camped'),
 ('camped', 'week'),
 ('week', 'north'),
 ('north', 'dakota'),
 ('dakota', 'standing'),
 ('standing', 'rock'),
 ('rock', 'sioux'),
 ('sioux', 'reservation'),
 ('reservation', 'protest'),
 ('protest', 'pipeline'),
 ('pipeline', 'construction'),
 ('construction', 'said'),
 ('said', 'protester'),
 ('protester', 'would'),
 ('would', 'continue'),
 ('continue', 'take'),
 ('take', 'advantage'),
 ('advantage', 'vulnerability'),
 ('vulnerability', 'energy'),
 ('energy', 'infrastructure'),
 ('infrastructure', 'pipeline'),
 ('pipeline', 'tanker'),
 ('tanker', 'train'),
 ('train', 'go'),
 ('go', 'thousand'),
 ('thousand', 'mile'),
 ('mile', 'could'),
 ('could', 'potential'),
 ('potential', 'protest'),
 ('protest', 'target'),
 ('target', 'said'),
 ('said', 'well'),
 ('well', 'established'),
 ('established', 'national'),
 ('national', 'environmental'),
 ('environmental', 'organization'),
 ('organization', 'helped'),
 ('helped', 'draft'),
 ('draft', 'obama'),
 ('obama', 'administration'),
 ('administration', 'environmental'),
 ('environmental', 'initiative'),
 ('initiative', 'like'),
 ('like', 'clean'),
 ('clean', 'power'),
 ('power', 'plan'),
 ('plan', 'curb'),
 ('curb', 'carbon'),
 ('carbon', 'dioxide'),
 ('dioxide', 'emission'),
 ('emission', 'shifting'),
 ('shifting', 'defensive'),
 ('defensive', 'posture'),
 ('posture', 'trump'),
 ('trump', 'leadership'),
 ('leadership', 'well'),
 ('well', 'congress'),
 ('congress', 'court'),
 ('court', 'boardroom'),
 ('boardroom', 'street'),
 ('street', 'said'),
 ('said', 'gene'),
 ('gene', 'karpinski'),
 ('karpinski', 'president'),
 ('president', 'washingtonbased'),
 ('washingtonbased', 'league'),
 ('league', 'conservation'),
 ('conservation', 'voter'),
 ('voter', 'backed'),
 ('backed', 'trump'),
 ('trump', 'democratic'),
 ('democratic', 'rival'),
 ('rival', 'hillary'),
 ('hillary', 'clinton'),
 ('clinton', 'spent'),
 ('spent', '45'),
 ('45', 'million'),
 ('million', 'support'),
 ('support', 'candidate'),
 ('candidate', '2016'),
 ('2016', 'election'),
 ('election', 'karpinski'),
 ('karpinski', 'said'),
 ('said', 'expected'),
 ('expected', 'legal'),
 ('legal', 'action'),
 ('action', 'prevent'),
 ('prevent', 'trump'),
 ('trump', 'following'),
 ('following', 'agenda'),
 ('agenda', 'trump'),
 ('trump', 'appointed'),
 ('appointed', 'myron'),
 ('myron', 'ebell'),
 ('ebell', 'known'),
 ('known', 'climate'),
 ('climate', 'skeptic'),
 ('skeptic', 'guide'),
 ('guide', 'reshaping'),
 ('reshaping', 'epa'),
 ('epa', 'trump'),
 ('trump', 'energy'),
 ('energy', 'adviser'),
 ('adviser', 'kevin'),
 ('kevin', 'cramer'),
 ('cramer', 'u'),
 ('u', 'representative'),
 ('representative', 'north'),
 ('north', 'dakota'),
 ('dakota', 'said'),
 ('said', 'trump'),
 ('trump', 'likely'),
 ('likely', 'target'),
 ('target', 'clean'),
 ('clean', 'power'),
 ('power', 'plan'),
 ('plan', 'water'),
 ('water', 'united'),
 ('united', 'state'),
 ('state', 'rule'),
 ('rule', 'first'),
 ('first', '100'),
 ('100', 'day'),
 ('day', 'office'),
 ('office', 'dan'),
 ('dan', 'farber'),
 ('farber', 'environmental'),
 ('environmental', 'law'),
 ('law', 'professor'),
 ('professor', 'university'),
 ('university', 'california'),
 ('california', 'berkeley'),
 ('berkeley', 'school'),
 ('school', 'law'),
 ('law', 'said'),
 ('said', 'best'),
 ('best', 'advocate'),
 ('advocate', 'climate'),
 ('climate', 'change'),
 ('change', 'action'),
 ('action', 'could'),
 ('could', 'hope'),
 ('hope', 'court'),
 ('court', 'play'),
 ('play', 'successful'),
 ('successful', 'defense'),
 ('defense', 'antienvironmental'),
 ('antienvironmental', 'onslaught'),
 ('onslaught', 'new'),
 ('new', 'administration'),
 ('administration', 'fairly'),
 ('fairly', 'grim'),
 ('grim', 'situation'),
 ('situation', 'added'),
 ('added', 'several'),
 ('several', 'group'),
 ('group', 'also'),
 ('also', 'said'),
 ('said', 'would'),
 ('would', 'put'),
 ('put', 'greater'),
 ('greater', 'focus'),
 ('focus', 'statelevel'),
 ('statelevel', 'environmental'),
 ('environmental', 'initiative'),
 ('initiative', 'sidestep'),
 ('sidestep', 'trump'),
 ('trump', 'administration'),
 ('administration', 'sierra'),
 ('sierra', 'club'),
 ('club', 'headquartered'),
 ('headquartered', 'california'),
 ('california', 'said'),
 ('said', 'would'),
 ('would', 'push'),
 ('push', 'ahead'),
 ('ahead', 'beyond'),
 ('beyond', 'coal'),
 ('coal', 'campaign'),
 ('campaign', 'led'),
 ('led', 'retirement'),
 ('retirement', 'hundred'),
 ('hundred', 'coal'),
 ('coal', 'plant'),
 ('plant', 'since'),
 ('since', 'launched'),
 ('launched', 'decade'),
 ('decade', 'ago'),
 ('ago', 'campaign'),
 ('campaign', 'mobilizes'),
 ('mobilizes', 'local'),
 ('local', 'activist'),
 ('activist', 'lawyer'),
 ('lawyer', 'push'),
 ('push', 'utility'),
 ('utility', 'state'),
 ('state', 'regulator'),
 ('regulator', 'shutter'),
 ('shutter', 'older'),
 ('older', 'plant'),
 ('plant', 'replace'),
 ('replace', 'renewable'),
 ('renewable', 'energy'),
 ('energy', 'clearly'),
 ('clearly', 'going'),
 ('going', 'fight'),
 ('fight', 'resist'),
 ('resist', 'worst'),
 ('worst', 'impulse'),
 ('impulse', 'next'),
 ('next', 'administration'),
 ('administration', 'said'),
 ('said', 'michael'),
 ('michael', 'brune'),
 ('brune', 'sierra'),
 ('sierra', 'club'),
 ('club', 'executive'),
 ('executive', 'director'),
 ('director', 'also'),
 ('also', 'mindful'),
 ('mindful', 'despite'),
 ('despite', 'odds'),
 ('odds', 'able'),
 ('able', 'make'),
 ('make', 'great'),
 ('great', 'progress'),
 ('progress', 'bush'),
 ('bush', 'administration'),
 ('administration', 'hope'),
 ('hope', 'beijing'),
 ('beijing', 'reuters'),
 ('reuters', 'u'),
 ('u', 'presidentelect'),
 ('presidentelect', 'donald'),
 ('donald', 'trump'),
 ('trump', 'call'),
 ('call', 'taiwan'),
 ('taiwan', 'president'),
 ('president', 'tsai'),
 ('tsai', 'ingwen'),
 ('ingwen', 'petty'),
 ('petty', 'action'),
 ('action', 'taiwan'),
 ('taiwan', 'chinese'),
 ('chinese', 'foreign'),
 ('foreign', 'minister'),
 ('minister', 'wang'),
 ('wang', 'yi'),
 ('yi', 'said'),
 ('said', 'saturday'),
 ('saturday', 'hong'),
 ('hong', 'kongbased'),
 ('kongbased', 'phoenix'),
 ('phoenix', 'television'),
 ('television', 'reported'),
 ('reported', 'conversation'),
 ('conversation', 'first'),
 ('first', 'contact'),
 ('contact', 'taiwan'),
 ('taiwan', 'u'),
 ('u', 'presidentelect'),
 ('presidentelect', 'president'),
 ('president', 'since'),
 ('since', 'president'),
 ('president', 'jimmy'),
 ('jimmy', 'carter'),
 ('carter', 'switched'),
 ('switched', 'diplomatic'),
 ('diplomatic', 'recognition'),
 ('recognition', 'taiwan'),
 ('taiwan', 'china'),
 ('china', '1979'),
 ('1979', 'acknowledging'),
 ('acknowledging', 'taiwan'),
 ('taiwan', 'part'),
 ('part', 'one'),
 ('one', 'china'),
 ('china', 'taiwan'),
 ('taiwan', 'side'),
 ('side', 'engaging'),
 ('engaging', 'petty'),
 ('petty', 'action'),
 ('action', 'change'),
 ('change', 'one'),
 ('one', 'china'),
 ('china', 'structure'),
 ('structure', 'already'),
 ('already', 'formed'),
 ('formed', 'international'),
 ('international', 'community'),
 ('community', 'wang'),
 ('wang', 'said'),
 ('said', 'academic'),
 ('academic', 'forum'),
 ('forum', 'station'),
 ('station', 'said'),
 ('said', 'believe'),
 ('believe', 'wo'),
 ('wo', 'nt'),
 ('nt', 'change'),
 ('change', 'longstanding'),
 ('longstanding', 'one'),
 ('one', 'china'),
 ('china', 'policy'),
 ('policy', 'united'),
 ('united', 'state'),
 ('state', 'government'),
 ('government', 'one'),
 ('one', 'china'),
 ('china', 'principle'),
 ('principle', 'cornerstone'),
 ('cornerstone', 'healthy'),
 ('healthy', 'development'),
 ('development', 'sinous'),
 ('sinous', 'tie'),
 ('tie', 'hope'),
 ('hope', 'political'),
 ('political', 'basis'),
 ('basis', 'interfered'),
 ('interfered', 'damaged'),
 ('damaged', 'way'),
 ('way', 'defeated'),
 ('defeated', 'nationalist'),
 ('nationalist', 'force'),
 ('force', 'fled'),
 ('fled', 'taiwan'),
 ('taiwan', 'end'),
 ('end', 'civil'),
 ('civil', 'war'),
 ('war', 'communist'),
 ('communist', '1949'),
 ('1949', 'beijing'),
 ('beijing', 'never'),
 ('never', 'renounced'),
 ('renounced', 'use'),
 ('use', 'force'),
 ('force', 'bring'),
 ('bring', 'control'),
 ('control', 'china'),
 ('china', 'view'),
 ('view', 'wayward'),
 ('wayward', 'province'),
 ('province', 'taiwan'),
 ('taiwan', 'one'),
 ('one', 'china'),
 ('china', 'sensitive'),
 ('sensitive', 'policy'),
 ('policy', 'issue'),
 ('issue', 'china'),
 ('china', 'generally'),
 ('generally', 'lambastes'),
 ('lambastes', 'form'),
 ('form', 'official'),
 ('official', 'contact'),
 ('contact', 'foreign'),
 ('foreign', 'government'),
 ('government', 'taiwan'),
 ('taiwan', 'leader'),
 ('leader', 'china'),
 ('china', 'deeply'),
 ('deeply', 'suspicious'),
 ('suspicious', 'tsai'),
 ('tsai', 'election'),
 ('election', 'january'),
 ('january', 'belief'),
 ('belief', 'want'),
 ('want', 'push'),
 ('push', 'island'),
 ('island', 'formal'),
 ('formal', 'independence'),
 ('independence', 'red'),
 ('red', 'line'),
 ('line', 'beijing'),
 ('beijing', 'tsai'),
 ('tsai', 'said'),
 ('said', 'want'),
 ('want', 'maintain'),
 ('maintain', 'status'),
 ('status', 'quo'),
 ('quo', 'china'),
 ('china', 'want'),
 ('want', 'peaceful'),
 ('peaceful', 'relation'),
 ('relation', 'quebec'),
 ('quebec', 'city'),
 ('city', 'reuters'),
 ('reuters', 'u'),
 ('u', 'secretary'),
 ('secretary', 'state'),
 ('state', 'john'),
 ('john', 'kerry'),
 ('kerry', 'friday'),
 ('friday', 'said'),
 ('said', 'could'),
 ('could', 'comment'),
 ('comment', 'private'),
 ('private', 'email'),
 ('email', 'chain'),
 ('chain', 'predecessor'),
 ('predecessor', 'hillary'),
 ('hillary', 'clinton'),
 ('clinton', 'saying'),
 ('saying', 'withheld'),
 ('withheld', 'request'),
 ('request', 'u'),
 ('u', 'intelligence'),
 ('intelligence', 'community'),
 ('community', 'ca'),
 ('ca', 'nt'),
 ('nt', 'speak'),
 ('speak', 'specific'),
 ('specific', 'anything'),
 ('anything', 'respect'),
 ('respect', 'technicality'),
 ('technicality', 'content'),
 ('content', 'that'),
 ('that', 's'),
 ('s', 'job'),
 ('job', 'kerry'),
 ('kerry', 'told'),
 ('told', 'news'),
 ('news', 'conference'),
 ('conference', 'canada'),
 ('canada', 'do'),
 ('do', 'nt'),
 ('nt', 'know'),
 ('know', 'hand'),
 ('hand', 'san'),
 ('san', 'franciscowashington'),
 ('franciscowashington', 'reuters'),
 ('reuters', 'president'),
 ('president', 'donald'),
 ('donald', 'trump'),
 ('trump', 'suffered'),
 ('suffered', 'another'),
 ('another', 'legal'),
 ('legal', 'setback'),
 ('setback', 'monday'),
 ('monday', 'second'),
 ('second', 'federal'),
 ('federal', 'appeal'),
 ('appeal', 'court'),
 ('court', 'refused'),
 ('refused', 'revive'),
 ('revive', 'travel'),
 ('travel', 'ban'),
 ('ban', 'people'),
 ('people', 'entering'),
 ('entering', 'united'),
 ('united', 'state'),
 ('state', 'six'),
 ('six', 'muslimmajority'),
 ('muslimmajority', 'nation'),
 ('nation', 'dispute'),
 ('dispute', 'headed'),
 ('headed', 'u'),
 ('u', 'supreme'),
 ('supreme', 'court'),
 ('court', 'san'),
 ('san', 'franciscobased'),
 ('franciscobased', '9th'),
 ('9th', 'u'),
 ('u', 'circuit'),
 ('circuit', 'court'),
 ('court', 'appeal'),
 ('appeal', 'used'),
 ('used', 'narrow'),
 ('narrow', 'ground'),
 ('ground', 'reject'),
 ('reject', 'trump'),
 ('trump', 'administration'),
 ('administration', 'bid'),
 ('bid', 'undo'),
 ('undo', 'hawaii'),
 ('hawaii', 'federal'),
 ('federal', 'judge'),
 ('judge', 'decision'),
 ('decision', 'blocking'),
 ('blocking', 'temporary'),
 ('temporary', 'ban'),
 ('ban', 'said'),
 ('said', 'republican'),
 ('republican', 'president'),
 ('president', 'march'),
 ('march', '6'),
 ('6', 'order'),
 ('order', 'violated'),
 ('violated', 'existing'),
 ('existing', 'immigration'),
 ('immigration', 'law'),
 ('law', 'threejudge'),
 ('threejudge', 'panel'),
 ('panel', 'democratic'),
 ('democratic', 'appointee'),
 ('appointee', 'address'),
 ('address', 'whether'),
 ('whether', 'unconstitutional'),
 ('unconstitutional', 'discrimination'),
 ('discrimination', 'muslim'),
 ('muslim', 'second'),
 ('second', 'court'),
 ('court', 'richmond'),
 ('richmond', 'virginiabased'),
 ('virginiabased', '4th'),
 ('4th', 'u'),
 ('u', 'circuit'),
 ('circuit', 'court'),
 ('court', 'appeal'),
 ('appeal', 'may'),
 ('may', '25'),
 ('25', 'upheld'),
 ('upheld', 'maryland'),
 ('maryland', 'judge'),
 ('judge', 'ruling'),
 ('ruling', 'also'),
 ('also', 'blocked'),
 ('blocked', 'trump'),
 ('trump', '90day'),
 ('90day', 'ban'),
 ('ban', 'traveler'),
 ('traveler', 'libya'),
 ('libya', 'iran'),
 ('iran', 'somalia'),
 ('somalia', 'sudan'),
 ('sudan', 'syria'),
 ('syria', 'yemen'),
 ('yemen', '4th'),
 ('4th', 'circuit'),
 ('circuit', 'ruled'),
 ('ruled', 'ban'),
 ('ban', 'replaced'),
 ('replaced', 'earlier'),
 ('earlier', 'jan'),
 ('jan', '27'),
 ('27', 'one'),
 ('one', 'also'),
 ('also', 'blocked'),
 ('blocked', 'court'),
 ('court', 'drip'),
 ('drip', 'religious'),
 ('religious', 'intolerance'),
 ('intolerance', 'animus'),

In [118]:
fact_df[fact_df['pos'] == 'NOUN'].value_counts()

token       pos   ner
trump       NOUN          161
state       NOUN           86
government  NOUN           74
year        NOUN  DATE     59
country     NOUN           56
                         ...
hometown    NOUN            1
homeowner   NOUN            1
homeland    NOUN  ORG       1
holiday     NOUN  DATE      1
zoom        NOUN            1
Name: count, Length: 2117, dtype: int64

In [119]:
fake_df[fake_df['pos'] == 'NOUN'].value_counts()

token       pos   ner
trump       NOUN         198
time        NOUN          78
woman       NOUN          75
people      NOUN          75
state       NOUN          67
                        ...
hawk        NOUN           1
hatevia     NOUN           1
hashtag     NOUN           1
harrington  NOUN           1
landmark    NOUN           1
Name: count, Length: 2585, dtype: int64

In [113]:
fake_df

         token    pos       ner
0          two    NUM  CARDINAL
1        small    ADJ
2      problem   NOUN
3      analogy   NOUN
4        susan  PROPN
...        ...    ...       ...
22061     work   NOUN
22062   simple    ADJ
22063      via    ADP
22064   campus   NOUN
22065   reform   NOUN

[22066 rows x 3 columns]

In [120]:
fact_df['ner'].value_counts()

ner
               16412
ORG              943
PERSON           872
DATE             842
GPE              719
NORP             360
CARDINAL         327
PERCENT           75
ORDINAL           58
LOC               49
QUANTITY          42
MONEY             35
TIME              23
FAC               12
EVENT              6
LAW                4
PRODUCT            2
WORK_OF_ART        2
LANGUAGE           1
Name: count, dtype: int64

In [121]:
fake_df['ner'].value_counts()

ner
               18460
PERSON          1100
ORG              606
DATE             604
GPE              385
CARDINAL         364
NORP             299
TIME              70
ORDINAL           62
PERCENT           31
LOC               20
MONEY             18
FAC               15
QUANTITY          13
WORK_OF_ART        6
EVENT              6
PRODUCT            6
LAW                1
Name: count, dtype: int64

In [128]:
fact_df.groupby('ner')['token'].value_counts().reset_index()

              ner      token  count
0                       said    452
1                      trump    212
2                          u    169
3                  president    137
4                      state    129
...           ...        ...    ...
5864         TIME     monday      1
5865         TIME  overnight      1
5866         TIME    tuesday      1
5867  WORK_OF_ART      abadi      1
5868  WORK_OF_ART     arabic      1

[5869 rows x 3 columns]

In [129]:
fact_df.head(20)

            token    pos       ner
0      washington  PROPN       GPE
1         reuters  PROPN
2               u  PROPN
3         defense  PROPN       ORG
4       secretary  PROPN
5             jim  PROPN    PERSON
6          mattis  PROPN    PERSON
7            said   VERB
8          monday  PROPN      DATE
9          russia  PROPN       GPE
10        bombing   NOUN
11       usbacked    ADJ
12        fighter   NOUN
13          syria  PROPN       GPE
14      discussed   VERB
15        highest    ADJ
16          level   NOUN
17  communication   NOUN
18           link   NOUN
19            two    NUM  CARDINAL

In [132]:
for token in fact_nlp_doc:
    if token.text.lower() == 'trump':
        print(token.text, token.ent_type_)

trump PERSON
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump PERSON
trump PERSON
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump PERSON
trump PERSON
trump
trump
trump
trump
trump PERSON
trump
trump
trump
trump
trump
trump
trump
trump PERSON
trump
trump ORG
trump PERSON
trump
trump PERSON
trump PERSON
trump
trump
trump
trump
trump PERSON
trump
trump
trump PERSON
trump
trump
trump
trump PERSON
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump PERSON
trump
trump PERSON
trump
trump
trump DATE
trump
trump
trump
trump
trump
trump
trump
trump
trump PERSON
trump PERSON
trump
trump PERSON
trump
trump
trump PERSON
trump PERSON
trump
trump
trump
trump
trump
trump PERSON
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump PERSON
trump
trump PERSON
trump
trump ORG
trump
trump PERSON
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump PERSON
trump
trump PERSON
trump
trump
trump
trump
trump
trump
trump
trump
trump PERSON
trump
trump
trump
trump
trump
trump
trump PERSON
trump
trump
trump PERSON
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump PERSON
trump
trump
trump
trump
trump PERSON
trump
trump
trump
trump
trump PERSON
trump
trump
trump
trump
trump
trump PERSON
trump
trump
trump
trump
trump
trump PERSON
trump
trump
trump
trump
trump
trump
trump PERSON
trump PERSON
trump
trump PERSON
trump
trump PERSON
trump PERSON
trump PERSON
trump PERSON
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump PERSON
trump PERSON
trump
trump
trump PERSON
trump PERSON
trump
trump
trump
trump
trump
trump
trump
trump
trump
trump PERSON
trump
trump
trump
trump
trump
trump PERSON
trump
trump
trump
trump PERSON
trump
trump
trump
trump
trump
trump
trump PERSON
trump
trump
trump PERSON
trump
trump
trump PERSON
trump PERSON

In [133]:
fact_str

'WASHINGTON (Reuters) - U.S. Defense Secretary Jim Mattis said on Monday that Russia s bombing of U.S-backed fighters in Syria was being discussed at the highest levels and while a communication link between the two countries had worked to avoid such incidents, the strike over the weekend was a departure.  When you look at the fact that this is a change, you can imagine this is at the highest levels,  Mattis told reporters. Russia s Defense Ministry on Sunday rejected the allegations, saying its planes only targeted Islamic State militants and that it had warned the United States well in advance of its operational plans. BELFAST (Reuters) - Northern Ireland s political parties are rapidly running out of time to restore a devolved power-sharing government, Britain s minister for the region said on Monday, as he sought to avoid a return of direct rule from London.  The window of opportunity to restore devolution and to form an executive is closing rapidly as we move further into the autumn and with pressures in public services already evident, the need for intervention is becoming increasingly clear,  James Brokenshire told a news conference.  I don t want to have to take this action, my intent is for politicians in Northern Ireland to form an executive. I m not going to pretend that this is easy as clear differences remain but it does remain achievable.   (Reuters) - Seattle financial worker Harrison Karlewicz had been considering joining an environmental activist group for a while. The day after Donald Trump won the White House, he signed up. “That was a big push for me, kind of a wakeup call,” the 25-year-old said, after joining 350 Seattle, a group that stages mass protests against fossil fuel use. “I thought, ‘I don’t feel involved. I want to get out there.’” During his campaign, Trump said global warming was a hoax and called for the Environmental Protection Agency to be gutted. He promised to “cancel” the Paris climate agreement between the United States and nearly 200 other countries to slow climate change, and he pledged to revive the coal industry. Karlewicz represents what environmental activists say is the silver lining of Trump’s electoral victory: Environmentally minded people angered by the outcome are rallying to their cause. At 350 Seattle, people packed a volunteer drop-in meeting  after news of Trump’s confirmed win, said organizer Emily Johnston. The group blocked a rail line in Washington state that transports oil to Shell and Tesoro refineries earlier this year.  \xa0\xa0\xa0\xa0“This was surprising to me, because I personally was so shaken that I felt practically paralyzed, and I know many other people did, too,” Johnston said. “The fact that many others responded by immediately engaging is incredibly heartening.” Jay O’Hara, a Vermont-based climate-change activist with the Climate Disobedience Center and a mastermind behind a coal shipment blockade in 2013 that spurred more radical fossil fuel activism, said Trump’s win represents an opportunity for environmentalists to focus on a clear enemy. “In some ways, it can almost be seen as a relief,” he said of Trump’s win. “We are going to have a real fight here, or maybe an actual argument.” Johnston, of 350 Seattle, who camped for a week at North Dakota’s Standing Rock Sioux reservation to protest pipeline construction, said that protesters would continue to take advantage of the vulnerability of energy infrastructure. “All these pipelines, all these tankers, all these trains have to go through thousands of miles” and could be potential protest targets, she said. Some of the well established national environmental organizations that helped draft the Obama administration’s environmental initiatives, like the Clean Power Plan to curb carbon dioxide emissions, will be shifting to a defensive posture under Trump’s leadership. “We’ll be in the Congress, in the courts, in the boardrooms and in the streets,” said Gene Karpinski, president of the Washington-based League of Conservation Voters, which backed Trump’s Democratic rival Hillary Clinton and spent over $45 million to support candidates in the 2016 elections. Karpinski said he expected legal action to prevent Trump from following through on his agenda.  Trump has appointed Myron Ebell, a known climate skeptic, to guide the reshaping of the EPA, and Trump energy adviser Kevin Cramer, a U.S. representative from North Dakota, said Trump is likely to target the Clean Power Plan and Waters of the United States rules during his first 100 days in office. Dan Farber, an environmental law professor at the University of California, Berkeley School of Law, said the best that advocates for climate change action could hope for from  courts is to “play successful defense against an anti-environmental onslaught” from the new administration. \xa0\xa0\xa0 “It’s a fairly grim situation,” he added. Several groups also said they would put a greater focus on state-level environmental initiatives to sidestep Trump’s administration.  The Sierra Club, which is headquartered in California, said it would push ahead with its Beyond Coal campaign, which has led to the retirement of hundreds of coal plants since it was launched more than a decade ago. The campaign mobilizes local activists and lawyers to push utilities and state regulators to shutter older plants and replace them with renewable energy.  “Clearly, we are going to have to fight and resist the worst impulses of the next administration,” said Michael Brune, Sierra Club’s executive director. “But we are also mindful that despite all odds, we were able to make great progress during the Bush administration and we hope to do it again.” BEIJING (Reuters) - U.S. President-elect Donald Trump’s call with Taiwan President Tsai Ing-wen was a “petty action” by Taiwan, Chinese Foreign Minister Wang Yi said on Saturday, Hong Kong-based Phoenix Television reported. The conversation was the first such contact with Taiwan by a U.S. president-elect or president since President Jimmy Carter switched diplomatic recognition from Taiwan to China in 1979, acknowledging Taiwan as part of “one China”. “This is just the Taiwan side engaging in a petty action, and cannot change the ‘one China’ structure already formed by the international community,” Wang said at an academic forum, the station said. “I believe that it won’t change the longstanding one China policy of the United States government. The ‘one China’ principle is the cornerstone of the healthy development of Sino-U.S. ties, and we hope this political basis is not interfered with or damaged in any way.” Defeated Nationalist forces fled to Taiwan at the end of a civil war with the Communists in 1949, and Beijing has never renounced the use of force to bring under its control what China views as a wayward province. Taiwan is one of China’s most sensitive policy issues, and China generally lambastes any form of official contact by foreign governments with Taiwan’s leaders. China is deeply suspicious of Tsai, who won election in January, and believes she wants to push for the island’s formal independence, a red line for Beijing. Tsai has said she wants to maintain the status quo with China and wants peaceful relations. QUEBEC CITY (Reuters) - U.S. Secretary of State John Kerry on Friday said he could not comment on private email chains of his predecessor Hillary Clinton, saying they were being withheld at the request of the U.S. intelligence community. “I can’t speak to the specifics of anything with respect to the technicalities, the contents ... because that’s not our job,” Kerry told a news conference in Canada. “We don’t know about it, it’s in other hands.” SAN FRANCISCO/WASHINGTON (Reuters) - President Donald Trump suffered another legal setback on Monday as a second federal appeals court refused to revive his travel ban on people entering the United States from six Muslim-majority nations in a dispute headed to the U.S. Supreme Court. The San Francisco-based 9th U.S. Circuit Court of Appeals  used narrow grounds to reject the Trump administration’s bid to undo a Hawaii federal judge’s decision blocking the temporary ban. It said the Republican president’s March 6 order violated existing immigration law. But the three-judge panel - all Democratic appointees - did not address whether it was unconstitutional discrimination against Muslims. A second court, the Richmond, Virginia-based 4th U.S. Circuit Court of Appeals, on May 25 upheld a Maryland judge’s ruling that also blocked Trump’s 90-day ban on travelers from Libya, Iran, Somalia, Sudan, Syria and Yemen.  The 4th Circuit had ruled that the ban, which replaced an earlier Jan. 27 one also blocked by the courts, “drips with religious intolerance, animus and discrimination” aimed at Muslims. The 9th Circuit largely left in place a nationwide injunction by Judge Derrick Watson that stopped parts of the order, which Trump said was urgently needed to prevent terrorism in the United States. That ruling came in a lawsuit challenging the order brought by the state of Hawaii, which stated the ban would harm its universities and tourism industry. Even before Monday’s ruling, the case was on the fast track to the Supreme Court, where the administration on June 1 filed an emergency request seeking to reinstate the order and hear its appeal of the 4th Circuit ruling. The Supreme Court could act on the administration’s request as soon as this week. Trump has been on the losing side in all four court rulings on the March order. White House spokesman Sean Spicer said the administration is reviewing Monday’s decision and expressed continued confidence that the order is fully lawful and ultimately will be upheld by the Supreme Court. “I think we can all attest that these are very dangerous times and we need every available tool at our disposal to prevent terrorists from entering the United States and committing acts of bloodshed and violence,” Spicer told a briefing. The 9th Circuit upheld the block on Trump’s three-month travel ban for the six countries and four-month suspension of all refugee admissions. But the court pared back part of Watson’s injunction in order to allow the government to conduct internal reviews on vetting procedures for these travelers. The administration said the travel ban was needed to allow time to implement stronger vetting measures, although it has already rolled out some new requirements not blocked by courts, including additional questions for visa applicants. Rather than focusing on Trump campaign statements as the Virginia-based court did, the 9th Circuit said the language in the executive order itself did not make a rational case for why a travel ban was needed. “The order does not offer a sufficient justification to suspend the entry of more than 180 million people on the basis of nationality,” the court wrote, referring the combined populations of the six countries.  Under immigration law, the administration was required to make findings that entry of the people in question would be detrimental to the United States but failed to do so, the court said. Stephen Vladeck, a professor at University of Texas School of Law, said the 9th Circuit provided an easier path for the Supreme Court to keep the travel ban on hold, because it avoided entirely the controversy over Trump’s campaign statements.  “It provides a very attractive way to leave the injunction in place without setting broader doctrinal rules about which they may have pause,” Vladeck said. Trump during the 2016 presidential campaign called for a “total and complete shutdown of Muslims entering the United States.” Monday was the deadline for the ban’s challengers to respond to the administration’s request that the order be allowed to go into effect. The American Civil Liberties Union, which represents people challenging the ban in the separate Maryland suit handled by the 4th Circuit, filed court papers urging the court not to take up the case, saying the order will become moot on Wednesday, 90 days from when Trump issued it. Lawyers for Hawaii called the order a “thinly veiled Muslim ban.” Trump’s earlier Jan. 27 order also included Iraq among the countries targeted and a total ban on refugees from Syria. The March order was intended to overcome the legal issues posed by the original ban, but was blocked before it could go into effect on March 16. The suits by Hawaii and the Maryland challengers argued that the order violated federal immigration law and a section of the Constitution’s First Amendment that prohibits the government from favoring or disfavoring any particular religion. Hawaii’s court papers mentioned a series of Trump Twitter posts on June 5. Trump described the order as a “watered down, politically correct” version of his original one. ANKARA (Reuters) - Turkey said on Monday its former economy minister, indicted in the United States for conspiring to violate U.S. sanctions on Iran, acted within international law and that charges against him amounted to a coup attempt through American courts. Former minister Zafer Caglayan  has protected Turkey s interests as Turkish economy minister, and has acted within the laws of our country and international laws while doing that,  government spokesman Bekir Bozdag said. The charges against Caglayan were  a repetition of the December FETO coup attempt ... through the American judiciary , Bozdag said, referring to 2013 leaks about alleged government corruption which were blamed on President Tayyip Erdogan s opponents. Caglayan and the ex-head of a state-owned Turkish bank were charged on Wednesday with conspiring to violate U.S. sanctions on Iran by illegally moving hundreds of millions of dollars through the U.S. financial system on Tehran s behalf. [nL8N1LO4RO] The charges stem from the case against Reza Zarrab, a wealthy Turkish-Iranian gold trader who was arrested in the United States over sanctions evasion last year. He has pleaded not guilty. Wednesday s indictment marked the first time an ex-government member with close ties to Erdogan had been charged in the investigation that has strained ties between Washington and Ankara.  Erdogan said last week he had told Washington that Turkey had never agreed to comply with its sanctions on Iran, and called on the United States to review the indictment. Turkey s presidency said on Saturday Erdogan spoke by phone with U.S. President Donald Trump. It did not say whether the two leaders discussed the case. [nL5N1LQ0HV] Bozdag also condemned the indictment of Erdogan s guards over violence during his visit to Washington in June, saying it relied on testimony from supporters of the outlawed militant PKK group, and had done  great damage  to U.S.-Turkish ties.WASHINGTON (Reuters) - U.S. President Donald Trump declined to say on Wednesday whether he will visit the Korean Peninsula’s demilitarized zone during an upcoming Asia tour. “I’d rather not say, but you’ll be surprised,” Trump told reporters on the White House South Lawn as he prepared to depart on a trip to Dallas.  Trump is scheduled to depart on Nov. 3 on a trip that includes visits to Japan, South Korea, China, Vietnam and the Philippines. His trip is expected to be heavily dominated by the nuclear and ballistic missile threat that North Korea poses. The DMZ is a border barrier between South and North Korea and is a traditional stop for American dignitaries. White House officials say Trump is to visit South Korea’s Camp Humphreys during his visit to South Korea to hail the U.S.-South Korean alliance.  There are no concerns about what message Trump would send by not going to the DMZ, a senior White House official told reporters on Monday. “The message is that we are guests during a state visit of President Moon Jae-in, who’s invited us to make a visit to Camp Humphreys. So we’ll keep talking with the South Korean government to see if there are things that they want to adjust,” the official said. WASHINGTON (Reuters) - The U.S. House of Representatives is expected to vote overwhelmingly on Tuesday for a bill that would slap new sanctions on Russia, Iran and North Korea, potentially complicating President Donald Trump’s hopes of pursuing improved relations with Moscow. The bipartisan measure aims to punish Russia for its 2014 annexation of Crimea from Ukraine and for alleged interference in the 2016 U.S. presidential election. The measure’s fate in the Senate is uncertain after a key senator said the deal announced over the weekend may not be final. Republican Senator Bob Corker, chairman of the Senate Foreign Relations Committee, told reporters that negotiators had a “very good weekend” but any announcement “seemed somewhat premature.” “We’re about there, there’s still some procedural issues we’re discussing but, you know, I think it worked out very, very well. We’ve still got a couple of things to talk about on North Korea,” Corker said. If the Republican-led Senate passes the measure, Trump will need to decide whether to sign the bill or veto it. Rejecting it would carry a risk that his veto could be overridden by lawmakers. The Trump administration has objected to a provision in the sanctions bill that the president obtain congressional approval before easing any sanctions on Moscow. “He’s going to study that legislation and see what the final product looks like,” White House spokeswoman Sarah Sanders told reporters on Monday, when asked whether Trump would support it. An earlier version of the bill, including sanctions on Russia and Iran, passed the Senate by 98-2 on June 15. A North Korea sanctions bill passed the House by 419-1 in May and House lawmakers were becoming increasingly impatient with the Senate’s failure to take up that legislation. House members saw the Iran and Russia sanctions bill as a chance to finally get the North Korea measure through the Senate. Trump’s relationship with Russia has been an issue during the first six months of his presidency as investigations continue into whether his associates colluded with Russian hackers to influence the election on his behalf. Russia denies interfering in the U.S. election. Trump has denied his campaign colluded with Moscow, calling the probes politically motivated and repeatedly criticizing them. In a series of tweets early on Tuesday, Trump lashed out at both U.S. Attorney General Jeff Sessions and Andrew McCabe, acting director of the Federal Bureau of Investigation. Without offering evidence, Trump cited “Ukrainian efforts to sabotage” his presidential campaign in order to aid his former Democratic rival, Hillary Clinton. Jared Kushner, Trump’s son-in-law and senior White House adviser, will visit Capitol Hill for a second straight day to be interviewed about his contacts with Russian officials during the 2016 campaign and the presidential transition. Trump on Tuesday praised Kushner, saying he had done “very well yesterday in proving he did not collude with the Russians.” GAZA (Reuters) - Rival Palestinian factions Fatah and Hamas agreed on Wednesday to delay final transfer of power of the Gaza Strip from Hamas to the Western-backed Palestinian government by 10 days to Dec. 10 to allow time to  complete arrangements , officials said. The factions signed a reconciliation deal brokered by Egypt last month after Hamas agreed to hand over administrative control of Gaza, including the key Rafah border crossing, a decade after seizing the enclave in a civil war. The deal bridges a bitter gulf between the Western-backed mainstream Fatah party of Palestinian President Mahmoud Abbas and Hamas, an Islamist movement designated as a terrorist group by Western countries and Israel. The agreement states that Hamas, which has disbanded its administration, would complete the handover by December 1 but disputes over the transfer process have emerged in recent days and Cairo has sent a senior security delegation to the territory to try to resolve the deadlock. In a brief joint statement, Fatah and 

In [134]:
fact_bi_grams

[('washington', 'reuters'),
 ('reuters', 'u'),
 ('u', 'defense'),
 ('defense', 'secretary'),
 ('secretary', 'jim'),
 ('jim', 'mattis'),
 ('mattis', 'said'),
 ('said', 'monday'),
 ('monday', 'russia'),
 ('russia', 'bombing'),
 ('bombing', 'usbacked'),
 ('usbacked', 'fighter'),
 ('fighter', 'syria'),
 ('syria', 'discussed'),
 ('discussed', 'highest'),
 ('highest', 'level'),
 ('level', 'communication'),
 ('communication', 'link'),
 ('link', 'two'),
 ('two', 'country'),
 ('country', 'worked'),
 ('worked', 'avoid'),
 ('avoid', 'incident'),
 ('incident', 'strike'),
 ('strike', 'weekend'),
 ('weekend', 'departure'),
 ('departure', 'look'),
 ('look', 'fact'),
 ('fact', 'change'),
 ('change', 'imagine'),
 ('imagine', 'highest'),
 ('highest', 'level'),
 ('level', 'mattis'),
 ('mattis', 'told'),
 ('told', 'reporter'),
 ('reporter', 'russia'),
 ('russia', 'defense'),
 ('defense', 'ministry'),
 ('ministry', 'sunday'),
 ('sunday', 'rejected'),
 ('rejected', 'allegation'),
 ('allegation', 'saying'),
 ('saying', 'plane'),
 ('plane', 'targeted'),
 ('targeted', 'islamic'),
 ('islamic', 'state'),
 ('state', 'militant'),
 ('militant', 'warned'),
 ('warned', 'united'),
 ('united', 'state'),
 ('state', 'well'),
 ('well', 'advance'),
 ('advance', 'operational'),
 ('operational', 'plan'),
 ('plan', 'belfast'),
 ('belfast', 'reuters'),
 ('reuters', 'northern'),
 ('northern', 'ireland'),
 ('ireland', 'political'),
 ('political', 'party'),
 ('party', 'rapidly'),
 ('rapidly', 'running'),
 ('running', 'time'),
 ('time', 'restore'),
 ('restore', 'devolved'),
 ('devolved', 'powersharing'),
 ('powersharing', 'government'),
 ('government', 'britain'),
 ('britain', 'minister'),
 ('minister', 'region'),
 ('region', 'said'),
 ('said', 'monday'),
 ('monday', 'sought'),
 ('sought', 'avoid'),
 ('avoid', 'return'),
 ('return', 'direct'),
 ('direct', 'rule'),
 ('rule', 'london'),
 ('london', 'window'),
 ('window', 'opportunity'),
 ('opportunity', 'restore'),
 ('restore', 'devolution'),
 ('devolution', 'form'),
 ('form', 'executive'),
 ('executive', 'closing'),
 ('closing', 'rapidly'),
 ('rapidly', 'move'),
 ('move', 'autumn'),
 ('autumn', 'pressure'),
 ('pressure', 'public'),
 ('public', 'service'),
 ('service', 'already'),
 ('already', 'evident'),
 ('evident', 'need'),
 ('need', 'intervention'),
 ('intervention', 'becoming'),
 ('becoming', 'increasingly'),
 ('increasingly', 'clear'),
 ('clear', 'james'),
 ('james', 'brokenshire'),
 ('brokenshire', 'told'),
 ('told', 'news'),
 ('news', 'conference'),
 ('conference', 'want'),
 ('want', 'take'),
 ('take', 'action'),
 ('action', 'intent'),
 ('intent', 'politician'),
 ('politician', 'northern'),
 ('northern', 'ireland'),
 ('ireland', 'form'),
 ('form', 'executive'),
 ('executive', 'going'),
 ('going', 'pretend'),
 ('pretend', 'easy'),
 ('easy', 'clear'),
 ('clear', 'difference'),
 ('difference', 'remain'),
 ('remain', 'remain'),
 ('remain', 'achievable'),
 ('achievable', 'reuters'),
 ('reuters', 'seattle'),
 ('seattle', 'financial'),
 ('financial', 'worker'),
 ('worker', 'harrison'),
 ('harrison', 'karlewicz'),
 ('karlewicz', 'considering'),
 ('considering', 'joining'),
 ('joining', 'environmental'),
 ('environmental', 'activist'),
 ('activist', 'group'),
 ('group', 'day'),
 ('day', 'donald'),
 ('donald', 'trump'),
 ('trump', 'white'),
 ('white', 'house'),
 ('house', 'signed'),
 ('signed', 'big'),
 ('big', 'push'),
 ('push', 'kind'),
 ('kind', 'wakeup'),
 ('wakeup', 'call'),
 ('call', '25yearold'),
 ('25yearold', 'said'),
 ('said', 'joining'),
 ('joining', '350'),
 ('350', 'seattle'),
 ('seattle', 'group'),
 ('group', 'stage'),
 ('stage', 'mass'),
 ('mass', 'protest'),
 ('protest', 'fossil'),
 ('fossil', 'fuel'),
 ('fuel', 'use'),
 ('use', 'thought'),
 ('thought', 'do'),
 ('do', 'nt'),
 ('nt', 'feel'),
 ('feel', 'involved'),
 ('involved', 'want'),
 ('want', 'get'),
 ('get', 'campaign'),
 ('campaign', 'trump'),
 ('trump', 'said'),
 ('said', 'global'),
 ('global', 'warming'),
 ('warming', 'hoax'),
 ('hoax', 'called'),
 ('called', 'environmental'),
 ('environmental', 'protection'),
 ('protection', 'agency'),
 ('agency', 'gutted'),
 ('gutted', 'promised'),
 ('promised', 'cancel'),
 ('cancel', 'paris'),
 ('paris', 'climate'),
 ('climate', 'agreement'),
 ('agreement', 'united'),
 ('united', 'state'),
 ('state', 'nearly'),
 ('nearly', '200'),
 ('200', 'country'),
 ('country', 'slow'),
 ('slow', 'climate'),
 ('climate', 'change'),
 ('change', 'pledged'),
 ('pledged', 'revive'),
 ('revive', 'coal'),
 ('coal', 'industry'),
 ('industry', 'karlewicz'),
 ('karlewicz', 'represents'),
 ('represents', 'environmental'),
 ('environmental', 'activist'),
 ('activist', 'say'),
 ('say', 'silver'),
 ('silver', 'lining'),
 ('lining', 'trump'),
 ('trump', 'electoral'),
 ('electoral', 'victory'),
 ('victory', 'environmentally'),
 ('environmentally', 'minded'),
 ('minded', 'people'),
 ('people', 'angered'),
 ('angered', 'outcome'),
 ('outcome', 'rallying'),
 ('rallying', 'cause'),
 ('cause', '350'),
 ('350', 'seattle'),
 ('seattle', 'people'),
 ('people', 'packed'),
 ('packed', 'volunteer'),
 ('volunteer', 'dropin'),
 ('dropin', 'meeting'),
 ('meeting', 'news'),
 ('news', 'trump'),
 ('trump', 'confirmed'),
 ('confirmed', 'win'),
 ('win', 'said'),
 ('said', 'organizer'),
 ('organizer', 'emily'),
 ('emily', 'johnston'),
 ('johnston', 'group'),
 ('group', 'blocked'),
 ('blocked', 'rail'),
 ('rail', 'line'),
 ('line', 'washington'),
 ('washington', 'state'),
 ('state', 'transport'),
 ('transport', 'oil'),
 ('oil', 'shell'),
 ('shell', 'tesoro'),
 ('tesoro', 'refinery'),
 ('refinery', 'earlier'),
 ('earlier', 'year'),
 ('year', 'surprising'),
 ('surprising', 'personally'),
 ('personally', 'shaken'),
 ('shaken', 'felt'),
 ('felt', 'practically'),
 ('practically', 'paralyzed'),
 ('paralyzed', 'know'),
 ('know', 'many'),
 ('many', 'people'),
 ('people', 'johnston'),
 ('johnston', 'said'),
 ('said', 'fact'),
 ('fact', 'many'),
 ('many', 'others'),
 ('others', 'responded'),
 ('responded', 'immediately'),
 ('immediately', 'engaging'),
 ('engaging', 'incredibly'),
 ('incredibly', 'heartening'),
 ('heartening', 'jay'),
 ('jay', 'ohara'),
 ('ohara', 'vermontbased'),
 ('vermontbased', 'climatechange'),
 ('climatechange', 'activist'),
 ('activist', 'climate'),
 ('climate', 'disobedience'),
 ('disobedience', 'center'),
 ('center', 'mastermind'),
 ('mastermind', 'behind'),
 ('behind', 'coal'),
 ('coal', 'shipment'),
 ('shipment', 'blockade'),
 ('blockade', '2013'),
 ('2013', 'spurred'),
 ('spurred', 'radical'),
 ('radical', 'fossil'),
 ('fossil', 'fuel'),
 ('fuel', 'activism'),
 ('activism', 'said'),
 ('said', 'trump'),
 ('trump', 'win'),
 ('win', 'represents'),
 ('represents', 'opportunity'),
 ('opportunity', 'environmentalist'),
 ('environmentalist', 'focus'),
 ('focus', 'clear'),
 ('clear', 'enemy'),
 ('enemy', 'way'),
 ('way', 'almost'),
 ('almost', 'seen'),
 ('seen', 'relief'),
 ('relief', 'said'),
 ('said', 'trump'),
 ('trump', 'win'),
 ('win', 'going'),
 ('going', 'real'),
 ('real', 'fight'),
 ('fight', 'maybe'),
 ('maybe', 'actual'),
 ('actual', 'argument'),
 ('argument', 'johnston'),
 ('johnston', '350'),
 ('350', 'seattle'),
 ('seattle', 'camped'),
 ('camped', 'week'),
 ('week', 'north'),
 ('north', 'dakota'),
 ('dakota', 'standing'),
 ('standing', 'rock'),
 ('rock', 'sioux'),
 ('sioux', 'reservation'),
 ('reservation', 'protest'),
 ('protest', 'pipeline'),
 ('pipeline', 'construction'),
 ('construction', 'said'),
 ('said', 'protester'),
 ('protester', 'would'),
 ('would', 'continue'),
 ('continue', 'take'),
 ('take', 'advantage'),
 ('advantage', 'vulnerability'),
 ('vulnerability', 'energy'),
 ('energy', 'infrastructure'),
 ('infrastructure', 'pipeline'),
 ('pipeline', 'tanker'),
 ('tanker', 'train'),
 ('train', 'go'),
 ('go', 'thousand'),
 ('thousand', 'mile'),
 ('mile', 'could'),
 ('could', 'potential'),
 ('potential', 'protest'),
 ('protest', 'target'),
 ('target', 'said'),
 ('said', 'well'),
 ('well', 'established'),
 ('established', 'national'),
 ('national', 'environmental'),
 ('environmental', 'organization'),
 ('organization', 'helped'),
 ('helped', 'draft'),
 ('draft', 'obama'),
 ('obama', 'administration'),
 ('administration', 'environmental'),
 ('environmental', 'initiative'),
 ('initiative', 'like'),
 ('like', 'clean'),
 ('clean', 'power'),
 ('power', 'plan'),
 ('plan', 'curb'),
 ('curb', 'carbon'),
 ('carbon', 'dioxide'),
 ('dioxide', 'emission'),
 ('emission', 'shifting'),
 ('shifting', 'defensive'),
 ('defensive', 'posture'),
 ('posture', 'trump'),
 ('trump', 'leadership'),
 ('leadership', 'well'),
 ('well', 'congress'),
 ('congress', 'court'),
 ('court', 'boardroom'),
 ('boardroom', 'street'),
 ('street', 'said'),
 ('said', 'gene'),
 ('gene', 'karpinski'),
 ('karpinski', 'president'),
 ('president', 'washingtonbased'),
 ('washingtonbased', 'league'),
 ('league', 'conservation'),
 ('conservation', 'voter'),
 ('voter', 'backed'),
 ('backed', 'trump'),
 ('trump', 'democratic'),
 ('democratic', 'rival'),
 ('rival', 'hillary'),
 ('hillary', 'clinton'),
 ('clinton', 'spent'),
 ('spent', '45'),
 ('45', 'million'),
 ('million', 'support'),
 ('support', 'candidate'),
 ('candidate', '2016'),
 ('2016', 'election'),
 ('election', 'karpinski'),
 ('karpinski', 'said'),
 ('said', 'expected'),
 ('expected', 'legal'),
 ('legal', 'action'),
 ('action', 'prevent'),
 ('prevent', 'trump'),
 ('trump', 'following'),
 ('following', 'agenda'),
 ('agenda', 'trump'),
 ('trump', 'appointed'),
 ('appointed', 'myron'),
 ('myron', 'ebell'),
 ('ebell', 'known'),
 ('known', 'climate'),
 ('climate', 'skeptic'),
 ('skeptic', 'guide'),
 ('guide', 'reshaping'),
 ('reshaping', 'epa'),
 ('epa', 'trump'),
 ('trump', 'energy'),
 ('energy', 'adviser'),
 ('adviser', 'kevin'),
 ('kevin', 'cramer'),
 ('cramer', 'u'),
 ('u', 'representative'),
 ('representative', 'north'),
 ('north', 'dakota'),
 ('dakota', 'said'),
 ('said', 'trump'),
 ('trump', 'likely'),
 ('likely', 'target'),
 ('target', 'clean'),
 ('clean', 'power'),
 ('power', 'plan'),
 ('plan', 'water'),
 ('water', 'united'),
 ('united', 'state'),
 ('state', 'rule'),
 ('rule', 'first'),
 ('first', '100'),
 ('100', 'day'),
 ('day', 'office'),
 ('office', 'dan'),
 ('dan', 'farber'),
 ('farber', 'environmental'),
 ('environmental', 'law'),
 ('law', 'professor'),
 ('professor', 'university'),
 ('university', 'california'),
 ('california', 'berkeley'),
 ('berkeley', 'school'),
 ('school', 'law'),
 ('law', 'said'),
 ('said', 'best'),
 ('best', 'advocate'),
 ('advocate', 'climate'),
 ('climate', 'change'),
 ('change', 'action'),
 ('action', 'could'),
 ('could', 'hope'),
 ('hope', 'court'),
 ('court', 'play'),
 ('play', 'successful'),
 ('successful', 'defense'),
 ('defense', 'antienvironmental'),
 ('antienvironmental', 'onslaught'),
 ('onslaught', 'new'),
 ('new', 'administration'),
 ('administration', 'fairly'),
 ('fairly', 'grim'),
 ('grim', 'situation'),
 ('situation', 'added'),
 ('added', 'several'),
 ('several', 'group'),
 ('group', 'also'),
 ('also', 'said'),
 ('said', 'would'),
 ('would', 'put'),
 ('put', 'greater'),
 ('greater', 'focus'),
 ('focus', 'statelevel'),
 ('statelevel', 'environmental'),
 ('environmental', 'initiative'),
 ('initiative', 'sidestep'),
 ('sidestep', 'trump'),
 ('trump', 'administration'),
 ('administration', 'sierra'),
 ('sierra', 'club'),
 ('club', 'headquartered'),
 ('headquartered', 'california'),
 ('california', 'said'),
 ('said', 'would'),
 ('would', 'push'),
 ('push', 'ahead'),
 ('ahead', 'beyond'),
 ('beyond', 'coal'),
 ('coal', 'campaign'),
 ('campaign', 'led'),
 ('led', 'retirement'),
 ('retirement', 'hundred'),
 ('hundred', 'coal'),
 ('coal', 'plant'),
 ('plant', 'since'),
 ('since', 'launched'),
 ('launched', 'decade'),
 ('decade', 'ago'),
 ('ago', 'campaign'),
 ('campaign', 'mobilizes'),
 ('mobilizes', 'local'),
 ('local', 'activist'),
 ('activist', 'lawyer'),
 ('lawyer', 'push'),
 ('push', 'utility'),
 ('utility', 'state'),
 ('state', 'regulator'),
 ('regulator', 'shutter'),
 ('shutter', 'older'),
 ('older', 'plant'),
 ('plant', 'replace'),
 ('replace', 'renewable'),
 ('renewable', 'energy'),
 ('energy', 'clearly'),
 ('clearly', 'going'),
 ('going', 'fight'),
 ('fight', 'resist'),
 ('resist', 'worst'),
 ('worst', 'impulse'),
 ('impulse', 'next'),
 ('next', 'administration'),
 ('administration', 'said'),
 ('said', 'michael'),
 ('michael', 'brune'),
 ('brune', 'sierra'),
 ('sierra', 'club'),
 ('club', 'executive'),
 ('executive', 'director'),
 ('director', 'also'),
 ('also', 'mindful'),
 ('mindful', 'despite'),
 ('despite', 'odds'),
 ('odds', 'able'),
 ('able', 'make'),
 ('make', 'great'),
 ('great', 'progress'),
 ('progress', 'bush'),
 ('bush', 'administration'),
 ('administration', 'hope'),
 ('hope', 'beijing'),
 ('beijing', 'reuters'),
 ('reuters', 'u'),
 ('u', 'presidentelect'),
 ('presidentelect', 'donald'),
 ('donald', 'trump'),
 ('trump', 'call'),
 ('call', 'taiwan'),
 ('taiwan', 'president'),
 ('president', 'tsai'),
 ('tsai', 'ingwen'),
 ('ingwen', 'petty'),
 ('petty', 'action'),
 ('action', 'taiwan'),
 ('taiwan', 'chinese'),
 ('chinese', 'foreign'),
 ('foreign', 'minister'),
 ('minister', 'wang'),
 ('wang', 'yi'),
 ('yi', 'said'),
 ('said', 'saturday'),
 ('saturday', 'hong'),
 ('hong', 'kongbased'),
 ('kongbased', 'phoenix'),
 ('phoenix', 'television'),
 ('television', 'reported'),
 ('reported', 'conversation'),
 ('conversation', 'first'),
 ('first', 'contact'),
 ('contact', 'taiwan'),
 ('taiwan', 'u'),
 ('u', 'presidentelect'),
 ('presidentelect', 'president'),
 ('president', 'since'),
 ('since', 'president'),
 ('president', 'jimmy'),
 ('jimmy', 'carter'),
 ('carter', 'switched'),
 ('switched', 'diplomatic'),
 ('diplomatic', 'recognition'),
 ('recognition', 'taiwan'),
 ('taiwan', 'china'),
 ('china', '1979'),
 ('1979', 'acknowledging'),
 ('acknowledging', 'taiwan'),
 ('taiwan', 'part'),
 ('part', 'one'),
 ('one', 'china'),
 ('china', 'taiwan'),
 ('taiwan', 'side'),
 ('side', 'engaging'),
 ('engaging', 'petty'),
 ('petty', 'action'),
 ('action', 'change'),
 ('change', 'one'),
 ('one', 'china'),
 ('china', 'structure'),
 ('structure', 'already'),
 ('already', 'formed'),
 ('formed', 'international'),
 ('international', 'community'),
 ('community', 'wang'),
 ('wang', 'said'),
 ('said', 'academic'),
 ('academic', 'forum'),
 ('forum', 'station'),
 ('station', 'said'),
 ('said', 'believe'),
 ('believe', 'wo'),
 ('wo', 'nt'),
 ('nt', 'change'),
 ('change', 'longstanding'),
 ('longstanding', 'one'),
 ('one', 'china'),
 ('china', 'policy'),
 ('policy', 'united'),
 ('united', 'state'),
 ('state', 'government'),
 ('government', 'one'),
 ('one', 'china'),
 ('china', 'principle'),
 ('principle', 'cornerstone'),
 ('cornerstone', 'healthy'),
 ('healthy', 'development'),
 ('development', 'sinous'),
 ('sinous', 'tie'),
 ('tie', 'hope'),
 ('hope', 'political'),
 ('political', 'basis'),
 ('basis', 'interfered'),
 ('interfered', 'damaged'),
 ('damaged', 'way'),
 ('way', 'defeated'),
 ('defeated', 'nationalist'),
 ('nationalist', 'force'),
 ('force', 'fled'),
 ('fled', 'taiwan'),
 ('taiwan', 'end'),
 ('end', 'civil'),
 ('civil', 'war'),
 ('war', 'communist'),
 ('communist', '1949'),
 ('1949', 'beijing'),
 ('beijing', 'never'),
 ('never', 'renounced'),
 ('renounced', 'use'),
 ('use', 'force'),
 ('force', 'bring'),
 ('bring', 'control'),
 ('control', 'china'),
 ('china', 'view'),
 ('view', 'wayward'),
 ('wayward', 'province'),
 ('province', 'taiwan'),
 ('taiwan', 'one'),
 ('one', 'china'),
 ('china', 'sensitive'),
 ('sensitive', 'policy'),
 ('policy', 'issue'),
 ('issue', 'china'),
 ('china', 'generally'),
 ('generally', 'lambastes'),
 ('lambastes', 'form'),
 ('form', 'official'),
 ('official', 'contact'),
 ('contact', 'foreign'),
 ('foreign', 'government'),
 ('government', 'taiwan'),
 ('taiwan', 'leader'),
 ('leader', 'china'),
 ('china', 'deeply'),
 ('deeply', 'suspicious'),
 ('suspicious', 'tsai'),
 ('tsai', 'election'),
 ('election', 'january'),
 ('january', 'belief'),
 ('belief', 'want'),
 ('want', 'push'),
 ('push', 'island'),
 ('island', 'formal'),
 ('formal', 'independence'),
 ('independence', 'red'),
 ('red', 'line'),
 ('line', 'beijing'),
 ('beijing', 'tsai'),
 ('tsai', 'said'),
 ('said', 'want'),
 ('want', 'maintain'),
 ('maintain', 'status'),
 ('status', 'quo'),
 ('quo', 'china'),
 ('china', 'want'),
 ('want', 'peaceful'),
 ('peaceful', 'relation'),
 ('relation', 'quebec'),
 ('quebec', 'city'),
 ('city', 'reuters'),
 ('reuters', 'u'),
 ('u', 'secretary'),
 ('secretary', 'state'),
 ('state', 'john'),
 ('john', 'kerry'),
 ('kerry', 'friday'),
 ('friday', 'said'),
 ('said', 'could'),
 ('could', 'comment'),
 ('comment', 'private'),
 ('private', 'email'),
 ('email', 'chain'),
 ('chain', 'predecessor'),
 ('predecessor', 'hillary'),
 ('hillary', 'clinton'),
 ('clinton', 'saying'),
 ('saying', 'withheld'),
 ('withheld', 'request'),
 ('request', 'u'),
 ('u', 'intelligence'),
 ('intelligence', 'community'),
 ('community', 'ca'),
 ('ca', 'nt'),
 ('nt', 'speak'),
 ('speak', 'specific'),
 ('specific', 'anything'),
 ('anything', 'respect'),
 ('respect', 'technicality'),
 ('technicality', 'content'),
 ('content', 'that'),
 ('that', 's'),
 ('s', 'job'),
 ('job', 'kerry'),
 ('kerry', 'told'),
 ('told', 'news'),
 ('news', 'conference'),
 ('conference', 'canada'),
 ('canada', 'do'),
 ('do', 'nt'),
 ('nt', 'know'),
 ('know', 'hand'),
 ('hand', 'san'),
 ('san', 'franciscowashington'),
 ('franciscowashington', 'reuters'),
 ('reuters', 'president'),
 ('president', 'donald'),
 ('donald', 'trump'),
 ('trump', 'suffered'),
 ('suffered', 'another'),
 ('another', 'legal'),
 ('legal', 'setback'),
 ('setback', 'monday'),
 ('monday', 'second'),
 ('second', 'federal'),
 ('federal', 'appeal'),
 ('appeal', 'court'),
 ('court', 'refused'),
 ('refused', 'revive'),
 ('revive', 'travel'),
 ('travel', 'ban'),
 ('ban', 'people'),
 ('people', 'entering'),
 ('entering', 'united'),
 ('united', 'state'),
 ('state', 'six'),
 ('six', 'muslimmajority'),
 ('muslimmajority', 'nation'),
 ('nation', 'dispute'),
 ('dispute', 'headed'),
 ('headed', 'u'),
 ('u', 'supreme'),
 ('supreme', 'court'),
 ('court', 'san'),
 ('san', 'franciscobased'),
 ('franciscobased', '9th'),
 ('9th', 'u'),
 ('u', 'circuit'),
 ('circuit', 'court'),
 ('court', 'appeal'),
 ('appeal', 'used'),
 ('used', 'narrow'),
 ('narrow', 'ground'),
 ('ground', 'reject'),
 ('reject', 'trump'),
 ('trump', 'administration'),
 ('administration', 'bid'),
 ('bid', 'undo'),
 ('undo', 'hawaii'),
 ('hawaii', 'federal'),
 ('federal', 'judge'),
 ('judge', 'decision'),
 ('decision', 'blocking'),
 ('blocking', 'temporary'),
 ('temporary', 'ban'),
 ('ban', 'said'),
 ('said', 'republican'),
 ('republican', 'president'),
 ('president', 'march'),
 ('march', '6'),
 ('6', 'order'),
 ('order', 'violated'),
 ('violated', 'existing'),
 ('existing', 'immigration'),
 ('immigration', 'law'),
 ('law', 'threejudge'),
 ('threejudge', 'panel'),
 ('panel', 'democratic'),
 ('democratic', 'appointee'),
 ('appointee', 'address'),
 ('address', 'whether'),
 ('whether', 'unconstitutional'),
 ('unconstitutional', 'discrimination'),
 ('discrimination', 'muslim'),
 ('muslim', 'second'),
 ('second', 'court'),
 ('court', 'richmond'),
 ('richmond', 'virginiabased'),
 ('virginiabased', '4th'),
 ('4th', 'u'),
 ('u', 'circuit'),
 ('circuit', 'court'),
 ('court', 'appeal'),
 ('appeal', 'may'),
 ('may', '25'),
 ('25', 'upheld'),
 ('upheld', 'maryland'),
 ('maryland', 'judge'),
 ('judge', 'ruling'),
 ('ruling', 'also'),
 ('also', 'blocked'),
 ('blocked', 'trump'),
 ('trump', '90day'),
 ('90day', 'ban'),
 ('ban', 'traveler'),
 ('traveler', 'libya'),
 ('libya', 'iran'),
 ('iran', 'somalia'),
 ('somalia', 'sudan'),
 ('sudan', 'syria'),
 ('syria', 'yemen'),
 ('yemen', '4th'),
 ('4th', 'circuit'),
 ('circuit', 'ruled'),
 ('ruled', 'ban'),
 ('ban', 'replaced'),
 ('replaced', 'earlier'),
 ('earlier', 'jan'),
 ('jan', '27'),
 ('27', 'one'),
 ('one', 'also'),
 ('also', 'blocked'),
 ('blocked', 'court'),
 ('court', 'drip'),
 ('drip', 'religious'),
 ('religious', 'intolerance'),
 ('intolerance', 'animus'),

In [135]:
ruler = nlp.add_pipe("entity_ruler", before="ner")

In [136]:
patterns = [
    # bigram pattern — two words together
    {"label": "PERSON", "pattern": [
        {"LOWER": "donald"}, {"LOWER": "trump"}
    ]},
    # unigram pattern — single word
    {"label": "PERSON", "pattern": [
        {"LOWER": "trump"}
    ]},
]

ruler.add_patterns(patterns)

In [137]:
new_fact_doc = nlp(fact_str)

In [138]:
for token in new_fact_doc:
    if token.text.lower() == 'trump':
        print(token.text, token.ent_type_)

Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON
Trump PERSON

In [156]:
fake_news_df.head()

,title,text,date,fake_or_factual,clean_text
0,HOLLYWEIRD LIB SUSAN SARANDON Compares Muslim ...,There are two small problems with your analogy...,"Dec 30, 2015",Fake News,small problem analogy susan jesus muslim josep...
1,Elijah Cummings Called Trump Out To His Face ...,Buried in Trump s bonkers interview with New Y...,"April 6, 2017",Fake News,bury trump s bonker interview new york times r...
2,Hillary Clinton Says Half Her Cabinet Will Be...,"Women make up over 50 percent of this country,...","April 26, 2016",Fake News,woman percent country grossly underrepresented...
3,Russian bombing of U.S.-backed forces being di...,WASHINGTON (Reuters) - U.S. Defense Secretary ...,"September 18, 2017",Factual News,washington reuters defense secretary jim matti...
4,Britain says window to restore Northern Irelan...,BELFAST (Reuters) - Northern Ireland s politic...,"September 4, 2017",Factual News,belfast reuters northern ireland s political p...

In [157]:
fake_news_df.drop(columns=['fake', 'fact'], inplace=True)

KeyError: "['fake', 'fact'] not found in axis"

In [150]:
def get_clean_text(text):
    doc = nlp(text)
    tokens = [word.lemma_.lower() for word in doc
              if not word.is_stop
              and not word.is_punct
              and not word.is_space
              and word.is_alpha
             ]
    return " ".join(tokens)

In [ ]:
fake_news_df["clean_text"] = fake_news_df["text"].apply(get_clean_text)

In [159]:
fake_news_df.head()

,title,text,date,fake_or_factual,clean_text
0,HOLLYWEIRD LIB SUSAN SARANDON Compares Muslim ...,There are two small problems with your analogy...,"Dec 30, 2015",Fake News,small problem analogy susan jesus muslim josep...
1,Elijah Cummings Called Trump Out To His Face ...,Buried in Trump s bonkers interview with New Y...,"April 6, 2017",Fake News,bury trump s bonker interview new york times r...
2,Hillary Clinton Says Half Her Cabinet Will Be...,"Women make up over 50 percent of this country,...","April 26, 2016",Fake News,woman percent country grossly underrepresented...
3,Russian bombing of U.S.-backed forces being di...,WASHINGTON (Reuters) - U.S. Defense Secretary ...,"September 18, 2017",Factual News,washington reuters defense secretary jim matti...
4,Britain says window to restore Northern Irelan...,BELFAST (Reuters) - Northern Ireland s politic...,"September 4, 2017",Factual News,belfast reuters northern ireland s political p...

In [162]:
## LDA

In [193]:
from sklearn.decomposition import LatentDirichletAllocation, TruncatedSVD

fake_bag_words_vector = CountVectorizer(ngram_range=(1,2))
fact_bag_words_vector = CountVectorizer(ngram_range=(1,2))

fake_vector_matrix = fake_bag_words_vector.fit_transform(fake_news_df[fake_news_df['fake_or_factual'] == 'Fake News']['clean_text'])
fact_vector_matrix = fact_bag_words_vector.fit_transform(fake_news_df[fake_news_df['fake_or_factual'] == 'Factual News']['clean_text'])

n_topics = 5

lda_fake = LatentDirichletAllocation(n_components=n_topics, random_state=42)
lda_fact = LatentDirichletAllocation(n_components=n_topics, random_state=42)

lda_fake.fit(fake_vector_matrix)
lda_fact.fit(fact_vector_matrix)

fake_feature_names = fake_bag_words_vector.get_feature_names_out()
for i, topic in enumerate(lda_fake.components_):
    print(f"Topic {i+1}:", 
          [fake_feature_names[j] for j in topic.argsort()[-10:][::-1]])

print('\n\n')
fact_feature_names = fact_bag_words_vector.get_feature_names_out()
for i, topic in enumerate(lda_fact.components_):
    print(f"Topic {i+1}:", 
          [fact_feature_names[j] for j in topic.argsort()[-10:][::-1]])

Topic 1: ['trump', 'say', 'clinton', 'state', 'email', 'hillary', 'woman', 'president', 'official', 'department']
Topic 2: ['president', 'trump', 'year', 'say', 'refugee', 'school', 'migrant', 'state', 'people', 'cruz']
Topic 3: ['trump', 'year', 'say', 'tell', 'official', 'bilderberg', 'president', 'room', 'boiler', 'know']
Topic 4: ['trump', 'say', 'woman', 'student', 'clinton', 'president', 'supporter', 'donald', 'state', 'attack']
Topic 5: ['trump', 'mccain', 'obama', 'say', 'syria', 'president', 'clinton', 'go', 'know', 'state']



Topic 1: ['say', 'trump', 'court', 'order', 'united', 'reuters', 'ban', 'president', 'campaign', 'committee']
Topic 2: ['say', 'trump', 'president', 'tax', 'reuters', 'year', 'putin', 'state', 'senate', 'party']
Topic 3: ['say', 'trump', 'reuters', 'refugee', 'state', 'korea', 'president', 'saudi', 'security', 'visit']
Topic 4: ['say', 'state', 'trump', 'government', 'year', 'law', 'court', 'reuters', 'bill', 'president']
Topic 5: ['say', 'trump', 'president', 'reuters', 'military', 'state', 'official', 'israel', 'united', 'government']

In [195]:
fake_tfidf = TfidfVectorizer(
    ngram_range=(1,2)
)

fact_tfidf = TfidfVectorizer(
    ngram_range=(1,2)
)

fake_vector_matrix = fake_tfidf.fit_transform(fake_news_df[fake_news_df['fake_or_factual'] == 'Fake News']['clean_text'])
fact_vector_matrix = fact_tfidf.fit_transform(fake_news_df[fake_news_df['fake_or_factual'] == 'Factual News']['clean_text'])

n_topics = 5

lsa_fake = TruncatedSVD(n_components=n_topics, random_state=42)
lsa_fact = TruncatedSVD(n_components=n_topics, random_state=42)

lsa_fake.fit(fake_vector_matrix)
lsa_fact.fit(fact_vector_matrix)

fake_feature_names = fake_tfidf.get_feature_names_out()
for i, topic in enumerate(lsa_fake.components_):
    print(f"Topic {i+1}:", 
          [fake_feature_names[j] for j in topic.argsort()[-10:][::-1]])

print('\n\n')
fact_feature_names = fact_tfidf.get_feature_names_out()
for i, topic in enumerate(lsa_fact.components_):
    print(f"Topic {i+1}:", 
          [fact_feature_names[j] for j in topic.argsort()[-10:][::-1]])

Topic 1: ['trump', 'clinton', 'president', 'say', 'woman', 'hillary', 'donald', 'donald trump', 'vote', 'obama']
Topic 2: ['boiler', 'boiler room', 'room', 'acr', 'pm', 'radio', 'broadcast', 'join', 'tune', 'political animal']
Topic 3: ['trump', 'conference', 'donald trump', 'press conference', 'donald', 'vote', 'conway', 'trump supporter', 'supporter', 'test']
Topic 4: ['flynn', 'clinton', 'email', 'hillary', 'conference', 'immunity', 'department', 'press conference', 'campaign', 'dnc']
Topic 5: ['flynn', 'source', 'russia', 'immunity', 'russian', 'administration', 'mccain', 'manafort', 'sanction', 'march']



Topic 1: ['trump', 'say', 'president', 'court', 'state', 'house', 'bill', 'obama', 'order', 'white']
Topic 2: ['korea', 'south', 'north korea', 'china', 'north', 'south korea', 'japanese', 'missile', 'visit', 'tokyo']
Topic 3: ['korea', 'trump', 'north korea', 'north', 'south', 'japanese', 'south korea', 'abe', 'tokyo', 'japan']
Topic 4: ['court', 'ban', 'order', 'refugee', 'judge', 'supreme', 'supreme court', 'circuit', 'case', 'korea']
Topic 5: ['trump', 'russia', 'putin', 'comey', 'israel', 'obama', 'russian', 'white house', 'white', 'sessions']

In [209]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.feature_extraction.text import TfidfVectorizer

X = fake_news_df['clean_text']
Y = fake_news_df['fake_or_factual']

tfidf = TfidfVectorizer(ngram_range=(1,2))
X_vectorized = tfidf.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X_vectorized, Y, test_size=0.3, random_state=42)

lr_model = LogisticRegression(random_state=42)
lr_model.fit(X_train, Y_train)

Y_predict = lr_model.predict(X_test)
print(accuracy_score(Y_test, Y_predict))


print(classification_report(Y_test, Y_predict))

0.8666666666666667
              precision    recall  f1-score   support

Factual News       0.88      0.88      0.88        32
   Fake News       0.86      0.86      0.86        28

    accuracy                           0.87        60
   macro avg       0.87      0.87      0.87        60
weighted avg       0.87      0.87      0.87        60

In [208]:
print("Total rows:", len(fake_news_df))
print("Fake News:", len(fake_news_df[fake_news_df['fake_or_factual'] == 'Fake News']))
print("Factual News:", len(fake_news_df[fake_news_df['fake_or_factual'] == 'Factual News']))

Total rows: 198
Fake News: 98
Factual News: 100

In [210]:
# Predict news

In [235]:
def predict_news(news):
    doc = nlp(news)
    tokens = [token.lemma_.lower() for token in doc
                if not token.is_punct
                and not token.is_space
                and not token.is_stop
                and token.is_alpha
             ]
    news_vector = tfidf.transform([" ".join(tokens)])
    news_predict = lr_model.predict(news_vector)[0]
    news_probability = lr_model.predict_proba(news_vector).flatten()

    print(lr_model.classes_)

    print(f'\nPrediction:   {news_predict}')
    print(f'Factual News: {news_probability[0]:.2f}')
    print(f'Fake News:    {news_probability[1]:.2f}')

In [241]:
predict_news("Hillary Clinton email server was used to hide classified information from the FBI investigation")
predict_news("The boiler room radio broadcast exposed the bilderberg secret group conspiracy")
predict_news("North Korea launched missiles over Japan as United States and South Korea discussed military response")
predict_news("obama attacks israel")

['Factual News' 'Fake News']

Prediction:   Fake News
Factual News: 0.40
Fake News:    0.60
['Factual News' 'Fake News']

Prediction:   Fake News
Factual News: 0.41
Fake News:    0.59
['Factual News' 'Fake News']

Prediction:   Factual News
Factual News: 0.57
Fake News:    0.43
['Factual News' 'Fake News']

Prediction:   Factual News
Factual News: 0.54
Fake News:    0.46